//! Client methods for the "Admin" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response};

/// Typed HTTP client for Admin endpoints.
pub struct AdminClient {
    client: PlatformClient,
}

impl AdminClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/payments/admin/consistency-check`
    pub async fn consistency_check(&self, claims: &VerifiedClaims) -> Result<ConsistencyCheckSchema, ClientError> {
        let path = format!("/api/payments/admin/consistency-check");
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/payments/admin/projection-status`
    pub async fn projection_status(&self, claims: &VerifiedClaims) -> Result<ProjectionStatusSchema, ClientError> {
        let path = format!("/api/payments/admin/projection-status");
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/payments/admin/projections`
    pub async fn list_projections(&self, claims: &VerifiedClaims) -> Result<PaginatedResponse<ProjectionSummarySchema>, ClientError> {
        let path = format!("/api/payments/admin/projections");
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
