//! Generated typed client for the Payments Service service.
//!
//! Auto-generated by client-codegen — do not edit.

pub mod types;
pub mod checkout_sessions;
pub mod payments;
pub mod webhooks;

pub use types::*;
pub use checkout_sessions::CheckoutSessionsClient;
pub use payments::PaymentsClient;
pub use webhooks::WebhooksClient;

// -- PlatformService trait impls (connects to SDK VerticalBuilder) --

impl platform_sdk::PlatformService for CheckoutSessionsClient {
    const SERVICE_NAME: &'static str = "payments";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for PaymentsClient {
    const SERVICE_NAME: &'static str = "payments";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for WebhooksClient {
    const SERVICE_NAME: &'static str = "payments";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

