//! Client methods for the "Webhooks" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_empty};

/// Typed HTTP client for Webhooks endpoints.
pub struct WebhooksClient {
    client: PlatformClient,
}

impl WebhooksClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/payments/webhook/tilled`
    pub async fn tilled_webhook(&self, claims: &VerifiedClaims) -> Result<(), ClientError> {
        let path = format!("/api/payments/webhook/tilled");
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
