//! Client methods for the "Portal" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response, parse_empty};

/// Typed HTTP client for Portal endpoints.
pub struct PortalClient {
    client: PlatformClient,
}

impl PortalClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/portal/me`
    pub async fn me(&self, claims: &VerifiedClaims) -> Result<MeResponse, ClientError> {
        let path = format!("/portal/me");
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/portal/party/{party_id}/probe`
    pub async fn party_guard_probe(&self, claims: &VerifiedClaims, party_id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("/portal/party/{}/probe", party_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
