//! Generated typed client for the Workforce Competence Service service.
//!
//! Auto-generated by client-codegen — do not edit.

pub mod types;
pub mod acceptance_authorities;
pub mod artifacts;
pub mod assignments;
pub mod authorization;

pub use types::*;
pub use acceptance_authorities::AcceptanceAuthoritiesClient;
pub use artifacts::ArtifactsClient;
pub use assignments::AssignmentsClient;
pub use authorization::AuthorizationClient;

// -- PlatformService trait impls (connects to SDK VerticalBuilder) --

impl platform_sdk::PlatformService for AcceptanceAuthoritiesClient {
    const SERVICE_NAME: &'static str = "workforce-competence";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for ArtifactsClient {
    const SERVICE_NAME: &'static str = "workforce-competence";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for AssignmentsClient {
    const SERVICE_NAME: &'static str = "workforce-competence";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for AuthorizationClient {
    const SERVICE_NAME: &'static str = "workforce-competence";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

