//! Client methods for the "Disposition" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response};

/// Typed HTTP client for Disposition endpoints.
pub struct DispositionClient {
    client: PlatformClient,
}

impl DispositionClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/quality-inspection/inspections/{inspection_id}/accept`
    pub async fn post_accept_inspection(&self, claims: &VerifiedClaims, inspection_id: uuid::Uuid, body: &DispositionTransitionRequest) -> Result<Inspection, ClientError> {
        let path = format!("/api/quality-inspection/inspections/{}/accept", inspection_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/quality-inspection/inspections/{inspection_id}/hold`
    pub async fn post_hold_inspection(&self, claims: &VerifiedClaims, inspection_id: uuid::Uuid, body: &DispositionTransitionRequest) -> Result<Inspection, ClientError> {
        let path = format!("/api/quality-inspection/inspections/{}/hold", inspection_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/quality-inspection/inspections/{inspection_id}/reject`
    pub async fn post_reject_inspection(&self, claims: &VerifiedClaims, inspection_id: uuid::Uuid, body: &DispositionTransitionRequest) -> Result<Inspection, ClientError> {
        let path = format!("/api/quality-inspection/inspections/{}/reject", inspection_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/quality-inspection/inspections/{inspection_id}/release`
    pub async fn post_release_inspection(&self, claims: &VerifiedClaims, inspection_id: uuid::Uuid, body: &DispositionTransitionRequest) -> Result<Inspection, ClientError> {
        let path = format!("/api/quality-inspection/inspections/{}/release", inspection_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
