//! Type definitions for the Quality Inspection Service client.
//!
//! Auto-generated by client-codegen — do not edit.

#![allow(unused_imports)]

use crate::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Pagination metadata for list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginationMeta {
    pub page: i64,
    pub page_size: i64,
    pub total_items: i64,
    pub total_pages: i64,
}

/// Generic paginated response envelope.
///
/// Local definition without `ToSchema` bound — client crates don't need
/// OpenAPI schema derivation. Wire-compatible with `platform_http_contracts::PaginatedResponse`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedResponse<T> {
    pub data: Vec<T>,
    pub pagination: PaginationMeta,
}

/// Simple wrapper for sub-collection list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataResponse<T> {
    pub data: Vec<T>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Characteristic {
    pub characteristic_type: String,
    #[serde(default)]
    pub key_characteristic: bool,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nominal: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tolerance_high: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tolerance_low: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uom: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateFinalInspectionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inspector_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lot_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_revision: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    pub wo_id: uuid::Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateInProcessInspectionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inspector_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lot_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub op_instance_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_revision: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    pub wo_id: uuid::Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateInspectionPlanRequest {
    pub characteristics: Vec<Characteristic>,
    pub part_id: uuid::Uuid,
    pub plan_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sample_size: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sampling_method: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateReceivingInspectionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inspector_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lot_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_revision: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub receipt_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DispositionTransitionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inspector_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Inspection {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub disposition: String,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inspected_at: Option<chrono::DateTime<chrono::Utc>>,
    pub inspection_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inspector_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lot_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub op_instance_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_revision: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub receipt_id: Option<uuid::Uuid>,
    pub result: String,
    pub tenant_id: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wo_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InspectionPlan {
    pub characteristics: serde_json::Value,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: uuid::Uuid,
    pub part_id: uuid::Uuid,
    pub plan_name: String,
    pub revision: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sample_size: Option<i32>,
    pub sampling_method: String,
    pub status: String,
    pub tenant_id: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}
