//! Client methods for the "Instances" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, build_query_url, parse_response};

/// Query parameters for [`list_instances`].
#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct ListInstancesQuery {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub definition_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i64>,
}

/// Typed HTTP client for Instances endpoints.
pub struct InstancesClient {
    client: PlatformClient,
}

impl InstancesClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/workflow/instances`
    pub async fn list_instances(&self, claims: &VerifiedClaims, query: &ListInstancesQuery) -> Result<PaginatedResponse<WorkflowInstance>, ClientError> {
        let path = format!("/api/workflow/instances");
        let url = build_query_url(&path, query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// Like [`list_instances`] but fetches all pages into a single `Vec`.
    pub async fn list_instances_all(&self, claims: &VerifiedClaims, query: &ListInstancesQuery) -> Result<Vec<WorkflowInstance>, ClientError> {
        let mut all_data = Vec::new();
        let mut page: i64 = 1;
        loop {
            let mut q = query.clone();
            q.page = Some(page);
            q.page_size = Some(100);
            let resp = self.list_instances(claims, &q).await?;
            all_data.extend(resp.data);
            if page >= resp.pagination.total_pages {
                break;
            }
            page += 1;
        }
        Ok(all_data)
    }

    /// POST `/api/workflow/instances`
    pub async fn start_instance(&self, claims: &VerifiedClaims, body: &StartInstanceRequest) -> Result<WorkflowInstance, ClientError> {
        let path = format!("/api/workflow/instances");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/workflow/instances/{instance_id}`
    pub async fn get_instance(&self, claims: &VerifiedClaims, instance_id: uuid::Uuid) -> Result<WorkflowInstance, ClientError> {
        let path = format!("/api/workflow/instances/{}", instance_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PATCH `/api/workflow/instances/{instance_id}/advance`
    pub async fn advance_instance(&self, claims: &VerifiedClaims, instance_id: uuid::Uuid, body: &AdvanceInstanceRequest) -> Result<AdvanceResponse, ClientError> {
        let path = format!("/api/workflow/instances/{}/advance", instance_id);
        let url = path;
        let resp = self.client.patch(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/workflow/instances/{instance_id}/transitions`
    pub async fn list_transitions(&self, claims: &VerifiedClaims, instance_id: uuid::Uuid) -> Result<Vec<WorkflowTransition>, ClientError> {
        let path = format!("/api/workflow/instances/{}/transitions", instance_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
