//! Client methods for the "Instances" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, build_query_url, parse_response};

/// Typed HTTP client for Instances endpoints.
pub struct InstancesClient {
    client: PlatformClient,
}

impl InstancesClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/workflow/instances`
    pub async fn list_instances(&self, claims: &VerifiedClaims, entity_type: Option<&str>, entity_id: Option<&str>, status: Option<&str>, definition_id: Option<uuid::Uuid>, page: Option<i64>, page_size: Option<i64>) -> Result<PaginatedResponse<WorkflowInstance>, ClientError> {
        let path = format!("/api/workflow/instances");
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            entity_type: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            entity_id: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            status: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            definition_id: Option<uuid::Uuid>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page: Option<i64>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page_size: Option<i64>,
        }
        let query = Query {
            entity_type: entity_type.map(|s| s.to_string()),
            entity_id: entity_id.map(|s| s.to_string()),
            status: status.map(|s| s.to_string()),
            definition_id,
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/workflow/instances`
    pub async fn start_instance(&self, claims: &VerifiedClaims, body: &StartInstanceRequest) -> Result<WorkflowInstance, ClientError> {
        let path = format!("/api/workflow/instances");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/workflow/instances/{instance_id}`
    pub async fn get_instance(&self, claims: &VerifiedClaims, instance_id: uuid::Uuid) -> Result<WorkflowInstance, ClientError> {
        let path = format!("/api/workflow/instances/{}", instance_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PATCH `/api/workflow/instances/{instance_id}/advance`
    pub async fn advance_instance(&self, claims: &VerifiedClaims, instance_id: uuid::Uuid, body: &AdvanceInstanceRequest) -> Result<AdvanceResponse, ClientError> {
        let path = format!("/api/workflow/instances/{}/advance", instance_id);
        let url = path;
        let resp = self.client.patch(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/workflow/instances/{instance_id}/transitions`
    pub async fn list_transitions(&self, claims: &VerifiedClaims, instance_id: uuid::Uuid) -> Result<Vec<WorkflowTransition>, ClientError> {
        let path = format!("/api/workflow/instances/{}/transitions", instance_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
