//! Type definitions for the Workflow Service client.
//!
//! Auto-generated by client-codegen — do not edit.

#![allow(unused_imports)]

use crate::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Pagination metadata for list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginationMeta {
    pub page: i64,
    pub page_size: i64,
    pub total_items: i64,
    pub total_pages: i64,
}

/// Generic paginated response envelope.
///
/// Local definition without `ToSchema` bound — client crates don't need
/// OpenAPI schema derivation. Wire-compatible with `platform_http_contracts::PaginatedResponse`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedResponse<T> {
    pub data: Vec<T>,
    pub pagination: PaginationMeta,
}

/// Simple wrapper for sub-collection list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataResponse<T> {
    pub data: Vec<T>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdvanceInstanceRequest {
    pub action: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub tenant_id: String,
    pub to_step_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdvanceResponse {
    pub instance: WorkflowInstance,
    pub transition: WorkflowTransition,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateDefinitionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub initial_step_id: String,
    pub name: String,
    pub steps: serde_json::Value,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum InstanceStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StartInstanceRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
    pub definition_id: uuid::Uuid,
    pub entity_id: String,
    pub entity_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowDefinition {
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub id: uuid::Uuid,
    pub initial_step_id: String,
    pub is_active: bool,
    pub name: String,
    pub steps: serde_json::Value,
    pub tenant_id: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub version: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowInstance {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<chrono::DateTime<chrono::Utc>>,
    pub context: serde_json::Value,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub current_step_id: String,
    pub definition_id: uuid::Uuid,
    pub entity_id: String,
    pub entity_type: String,
    pub id: uuid::Uuid,
    pub started_at: chrono::DateTime<chrono::Utc>,
    pub status: InstanceStatus,
    pub tenant_id: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowTransition {
    pub action: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    pub from_step_id: String,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    pub instance_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub tenant_id: String,
    pub to_step_id: String,
    pub transitioned_at: chrono::DateTime<chrono::Utc>,
}
