//! Client methods for the "Numbering" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, parse_response};
use reqwest::Client;

/// Typed HTTP client for Numbering endpoints.
pub struct NumberingClient {
    client: Client,
    base_url: String,
    token: String,
}

impl NumberingClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// POST `/allocate`
    pub async fn allocate(&self, body: &AllocateRequest) -> Result<AllocateResponse, ClientError> {
        let path = format!("{}/allocate", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/confirm`
    pub async fn confirm(&self, body: &ConfirmRequest) -> Result<ConfirmResponse, ClientError> {
        let path = format!("{}/confirm", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
