//! Client methods for the "Policies" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, parse_response};
use reqwest::Client;

/// Typed HTTP client for Policies endpoints.
pub struct PoliciesClient {
    client: Client,
    base_url: String,
    token: String,
}

impl PoliciesClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/policies/{entity}`
    pub async fn get_policy(&self, entity: &str) -> Result<PolicyResponse, ClientError> {
        let path = format!("{}/policies/{}", self.base_url, entity);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/policies/{entity}`
    pub async fn upsert_policy(&self, entity: &str, body: &UpsertPolicyRequest) -> Result<PolicyResponse, ClientError> {
        let path = format!("{}/policies/{}", self.base_url, entity);
        let url = path;
        let resp = self.client.put(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
