//! Type definitions for the Numbering Service client.
//!
//! Auto-generated by client-codegen — do not edit.

#![allow(unused_imports)]

use serde::{Deserialize, Serialize};
use crate::*;

/// Pagination metadata for list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginationMeta {
    pub page: i64,
    pub page_size: i64,
    pub total_items: i64,
    pub total_pages: i64,
}

/// Generic paginated response envelope.
///
/// Local definition without `ToSchema` bound — client crates don't need
/// OpenAPI schema derivation. Wire-compatible with `platform_http_contracts::PaginatedResponse`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedResponse<T> {
    pub data: Vec<T>,
    pub pagination: PaginationMeta,
}

/// Simple wrapper for sub-collection list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataResponse<T> {
    pub data: Vec<T>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllocateRequest {
    pub entity: String,
    /// Enable gap-free mode for this sequence.  Only honoured on the first
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gap_free: Option<bool>,
    pub idempotency_key: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllocateResponse {
    pub entity: String,
    /// Present only for gap-free reservations — ISO 8601 expiry timestamp.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub formatted_number: Option<String>,
    pub idempotency_key: String,
    pub number_value: i64,
    pub replay: bool,
    /// "confirmed" for standard allocations, "reserved" for gap-free.
    pub status: String,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfirmRequest {
    pub entity: String,
    pub idempotency_key: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfirmResponse {
    pub entity: String,
    pub idempotency_key: String,
    pub number_value: i64,
    pub replay: bool,
    pub status: String,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PolicyResponse {
    pub entity: String,
    pub padding: i32,
    pub pattern: String,
    pub prefix: String,
    pub tenant_id: String,
    pub version: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpsertPolicyRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub padding: Option<i32>,
    pub pattern: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
}

