//! Client methods for the "templates" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::types::*;
use platform_sdk::{ClientError, parse_response};
use reqwest::Client;

/// Typed HTTP client for templates endpoints.
pub struct TemplatesClient {
    client: Client,
    base_url: String,
    token: String,
}

impl TemplatesClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/artifacts/{id}`
    pub async fn get_artifact(&self, id: uuid::Uuid) -> Result<RenderArtifact, ClientError> {
        let path = format!("{}/api/artifacts/{}", self.base_url, id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/templates`
    pub async fn create_template(&self, body: &CreateTemplateRequest) -> Result<DocTemplate, ClientError> {
        let path = format!("{}/api/templates", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/templates/{id}`
    pub async fn get_template(&self, id: uuid::Uuid) -> Result<DocTemplate, ClientError> {
        let path = format!("{}/api/templates/{}", self.base_url, id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/templates/{id}/render`
    pub async fn render_template(&self, id: uuid::Uuid, body: &RenderRequest) -> Result<RenderArtifact, ClientError> {
        let path = format!("{}/api/templates/{}/render", self.base_url, id);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
