//! Client methods for the "Approvals" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{build_query_url, parse_response, ClientError, PlatformClient, VerifiedClaims};

/// Typed HTTP client for Approvals endpoints.
pub struct ApprovalsClient {
    client: PlatformClient,
}

impl ApprovalsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/timekeeping/approvals`
    pub async fn list_approvals(
        &self,
        claims: &VerifiedClaims,
        employee_id: uuid::Uuid,
        from: chrono::NaiveDate,
        to: chrono::NaiveDate,
    ) -> Result<Vec<ApprovalRequest>, ClientError> {
        let path = format!("/api/timekeeping/approvals");
        #[derive(serde::Serialize)]
        struct Query {
            employee_id: uuid::Uuid,
            from: chrono::NaiveDate,
            to: chrono::NaiveDate,
        }
        let query = Query {
            employee_id,
            from,
            to,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self
            .client
            .get(&url, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/timekeeping/approvals/approve`
    pub async fn approve_approval(
        &self,
        claims: &VerifiedClaims,
        body: &ReviewApprovalRequest,
    ) -> Result<ApprovalRequest, ClientError> {
        let path = format!("/api/timekeeping/approvals/approve");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/timekeeping/approvals/pending`
    pub async fn list_pending(
        &self,
        claims: &VerifiedClaims,
    ) -> Result<Vec<ApprovalRequest>, ClientError> {
        let path = format!("/api/timekeeping/approvals/pending");
        let url = path;
        let resp = self
            .client
            .get(&url, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/timekeeping/approvals/recall`
    pub async fn recall_approval(
        &self,
        claims: &VerifiedClaims,
        body: &RecallApprovalRequest,
    ) -> Result<ApprovalRequest, ClientError> {
        let path = format!("/api/timekeeping/approvals/recall");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/timekeeping/approvals/reject`
    pub async fn reject_approval(
        &self,
        claims: &VerifiedClaims,
        body: &ReviewApprovalRequest,
    ) -> Result<ApprovalRequest, ClientError> {
        let path = format!("/api/timekeeping/approvals/reject");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/timekeeping/approvals/submit`
    pub async fn submit_approval(
        &self,
        claims: &VerifiedClaims,
        body: &SubmitApprovalRequest,
    ) -> Result<ApprovalRequest, ClientError> {
        let path = format!("/api/timekeeping/approvals/submit");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/timekeeping/approvals/{id}`
    pub async fn get_approval(
        &self,
        claims: &VerifiedClaims,
        id: uuid::Uuid,
    ) -> Result<ApprovalRequest, ClientError> {
        let path = format!("/api/timekeeping/approvals/{}", id);
        let url = path;
        let resp = self
            .client
            .get(&url, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/timekeeping/approvals/{id}/actions`
    pub async fn approval_actions(
        &self,
        claims: &VerifiedClaims,
        id: uuid::Uuid,
    ) -> Result<Vec<ApprovalAction>, ClientError> {
        let path = format!("/api/timekeeping/approvals/{}/actions", id);
        let url = path;
        let resp = self
            .client
            .get(&url, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
