//! Client methods for the "Projects" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{parse_response, ClientError, PlatformClient, VerifiedClaims};

/// Typed HTTP client for Projects endpoints.
pub struct ProjectsClient {
    client: PlatformClient,
}

impl ProjectsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/timekeeping/projects`
    pub async fn list_projects(
        &self,
        claims: &VerifiedClaims,
    ) -> Result<Vec<Project>, ClientError> {
        let path = format!("/api/timekeeping/projects");
        let url = path;
        let resp = self
            .client
            .get(&url, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/timekeeping/projects`
    pub async fn create_project(
        &self,
        claims: &VerifiedClaims,
        body: &CreateProjectRequest,
    ) -> Result<Project, ClientError> {
        let path = format!("/api/timekeeping/projects");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// DELETE `/api/timekeeping/projects/{id}`
    pub async fn deactivate_project(
        &self,
        claims: &VerifiedClaims,
        id: uuid::Uuid,
    ) -> Result<Project, ClientError> {
        let path = format!("/api/timekeeping/projects/{}", id);
        let url = path;
        let resp = self
            .client
            .delete(&url, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/timekeeping/projects/{id}`
    pub async fn get_project(
        &self,
        claims: &VerifiedClaims,
        id: uuid::Uuid,
    ) -> Result<Project, ClientError> {
        let path = format!("/api/timekeeping/projects/{}", id);
        let url = path;
        let resp = self
            .client
            .get(&url, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/timekeeping/projects/{id}`
    pub async fn update_project(
        &self,
        claims: &VerifiedClaims,
        id: uuid::Uuid,
        body: &UpdateProjectRequest,
    ) -> Result<Project, ClientError> {
        let path = format!("/api/timekeeping/projects/{}", id);
        let url = path;
        let resp = self
            .client
            .put(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
