//! Type definitions for the Timekeeping Service client.
//!
//! Auto-generated by client-codegen — do not edit.

#![allow(unused_imports)]

use serde::{Deserialize, Serialize};
use serde_json::Value;
use crate::*;

/// Pagination metadata for list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginationMeta {
    pub page: i64,
    pub page_size: i64,
    pub total_items: i64,
    pub total_pages: i64,
}

/// Generic paginated response envelope.
///
/// Local definition without `ToSchema` bound — client crates don't need
/// OpenAPI schema derivation. Wire-compatible with `platform_http_contracts::PaginatedResponse`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedResponse<T> {
    pub data: Vec<T>,
    pub pagination: PaginationMeta,
}

/// Simple wrapper for sub-collection list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataResponse<T> {
    pub data: Vec<T>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Allocation {
    pub active: bool,
    pub allocated_minutes_per_week: i32,
    pub app_id: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub effective_from: chrono::NaiveDate,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effective_to: Option<chrono::NaiveDate>,
    pub employee_id: uuid::Uuid,
    pub id: uuid::Uuid,
    pub project_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<uuid::Uuid>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalAction {
    pub action: String,
    pub actor_id: uuid::Uuid,
    pub approval_id: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalRequest {
    pub app_id: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub employee_id: uuid::Uuid,
    pub id: uuid::Uuid,
    pub period_end: chrono::NaiveDate,
    pub period_start: chrono::NaiveDate,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reviewed_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reviewer_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reviewer_notes: Option<String>,
    pub status: ApprovalStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub submitted_at: Option<chrono::DateTime<chrono::Utc>>,
    pub total_minutes: i32,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ApprovalStatus {
    Draft,
    Submitted,
    Approved,
    Rejected,
}

/// A single billing line item computed from an entry + its rate.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillingLineItem {
    pub amount_cents: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub entry_id: uuid::Uuid,
    pub minutes: i32,
    pub rate_cents_per_hour: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillingRate {
    pub app_id: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: uuid::Uuid,
    pub is_active: bool,
    pub name: String,
    pub rate_cents_per_hour: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillingRun {
    pub amount_cents: i64,
    pub app_id: String,
    pub ar_customer_id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ar_invoice_id: Option<i32>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub from_date: chrono::NaiveDate,
    pub id: uuid::Uuid,
    pub idempotency_key: String,
    pub status: String,
    pub to_date: chrono::NaiveDate,
}

/// Result returned by `create_billing_run`.
/// 
/// When `already_ran = true`, the caller should use the existing `run`
/// without creating a duplicate AR invoice (idempotency).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillingRunResult {
    pub already_ran: bool,
    pub line_items: Vec<BillingLineItem>,
    pub run: BillingRun,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorrectEntryRequest {
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub entry_id: uuid::Uuid,
    pub minutes: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateAllocationRequest {
    pub allocated_minutes_per_week: i32,
    pub app_id: String,
    pub effective_from: chrono::NaiveDate,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effective_to: Option<chrono::NaiveDate>,
    pub employee_id: uuid::Uuid,
    pub project_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateBillingRateRequest {
    pub app_id: String,
    pub name: String,
    pub rate_cents_per_hour: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateBillingRunRequest {
    pub app_id: String,
    pub ar_customer_id: i32,
    pub from_date: chrono::NaiveDate,
    pub to_date: chrono::NaiveDate,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateEmployeeRequest {
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    pub employee_code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_payroll_id: Option<String>,
    pub first_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hourly_rate_minor: Option<i64>,
    pub last_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateEntryRequest {
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub employee_id: uuid::Uuid,
    pub minutes: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<uuid::Uuid>,
    pub work_date: chrono::NaiveDate,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateExportRunRequest {
    pub app_id: String,
    pub export_type: String,
    pub period_end: chrono::NaiveDate,
    pub period_start: chrono::NaiveDate,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateProjectRequest {
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub billable: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl_account_ref: Option<String>,
    pub name: String,
    pub project_code: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateTaskRequest {
    pub app_id: String,
    pub name: String,
    pub project_id: uuid::Uuid,
    pub task_code: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Employee {
    pub active: bool,
    pub app_id: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    pub employee_code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_payroll_id: Option<String>,
    pub first_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hourly_rate_minor: Option<i64>,
    pub id: uuid::Uuid,
    pub last_name: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmployeeRollup {
    pub employee_id: uuid::Uuid,
    pub entry_count: i64,
    pub first_name: String,
    pub last_name: String,
    pub total_minutes: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum EntryType {
    Original,
    Correction,
    Void,
}

/// Generated export artifacts returned to the caller.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportArtifact {
    pub csv: String,
    pub json: serde_json::Value,
    pub run: ExportRun,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportRun {
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_hash: Option<String>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    pub export_type: String,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub period_end: chrono::NaiveDate,
    pub period_start: chrono::NaiveDate,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub record_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::Utc>>,
    pub status: ExportStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ExportStatus {
    Pending,
    InProgress,
    Completed,
    Failed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Project {
    pub active: bool,
    pub app_id: String,
    pub billable: bool,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl_account_ref: Option<String>,
    pub id: uuid::Uuid,
    pub name: String,
    pub project_code: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectRollup {
    pub entry_count: i64,
    pub project_id: uuid::Uuid,
    pub project_name: String,
    pub total_minutes: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecallApprovalRequest {
    pub actor_id: uuid::Uuid,
    pub app_id: String,
    pub approval_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewApprovalRequest {
    pub actor_id: uuid::Uuid,
    pub app_id: String,
    pub approval_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubmitApprovalRequest {
    pub actor_id: uuid::Uuid,
    pub app_id: String,
    pub employee_id: uuid::Uuid,
    pub period_end: chrono::NaiveDate,
    pub period_start: chrono::NaiveDate,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Task {
    pub active: bool,
    pub app_id: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: uuid::Uuid,
    pub name: String,
    pub project_id: uuid::Uuid,
    pub task_code: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskRollup {
    pub entry_count: i64,
    pub project_id: uuid::Uuid,
    pub task_id: uuid::Uuid,
    pub task_name: String,
    pub total_minutes: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetEntry {
    pub app_id: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub employee_id: uuid::Uuid,
    pub entry_id: uuid::Uuid,
    pub entry_type: EntryType,
    pub id: i64,
    pub is_current: bool,
    pub minutes: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_id: Option<uuid::Uuid>,
    pub version: i32,
    pub work_date: chrono::NaiveDate,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateAllocationRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allocated_minutes_per_week: Option<i32>,
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effective_to: Option<chrono::NaiveDate>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateEmployeeRequest {
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_payroll_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hourly_rate_minor: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateProjectRequest {
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub billable: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl_account_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateTaskRequest {
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VoidEntryRequest {
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<uuid::Uuid>,
    pub entry_id: uuid::Uuid,
}

