//! Client methods for the "Accruals" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{parse_response, ClientError, PlatformClient, VerifiedClaims};

/// Typed HTTP client for Accruals endpoints.
pub struct AccrualsClient {
    client: PlatformClient,
}

impl AccrualsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/gl/accruals/create`
    pub async fn create_accrual_handler(
        &self,
        claims: &VerifiedClaims,
        body: &CreateAccrualRequest,
    ) -> Result<AccrualResult, ClientError> {
        let path = format!("/api/gl/accruals/create");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/gl/accruals/reversals/execute`
    pub async fn execute_reversals_handler(
        &self,
        claims: &VerifiedClaims,
        body: &ExecuteReversalsRequest,
    ) -> Result<ExecuteReversalsResult, ClientError> {
        let path = format!("/api/gl/accruals/reversals/execute");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/gl/accruals/templates`
    pub async fn create_template_handler(
        &self,
        claims: &VerifiedClaims,
        body: &CreateTemplateRequest,
    ) -> Result<TemplateResult, ClientError> {
        let path = format!("/api/gl/accruals/templates");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
