//! Client methods for the "Close Checklist" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response};

/// Typed HTTP client for Close Checklist endpoints.
pub struct CloseChecklistClient {
    client: PlatformClient,
}

impl CloseChecklistClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/gl/periods/{period_id}/approvals`
    pub async fn get_approvals(&self, claims: &VerifiedClaims, period_id: uuid::Uuid) -> Result<Vec<ApprovalResponse>, ClientError> {
        let path = format!("/api/gl/periods/{}/approvals", period_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/gl/periods/{period_id}/approvals`
    pub async fn create_approval(&self, claims: &VerifiedClaims, period_id: uuid::Uuid, body: &CreateApprovalRequest) -> Result<ApprovalResponse, ClientError> {
        let path = format!("/api/gl/periods/{}/approvals", period_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/gl/periods/{period_id}/checklist`
    pub async fn get_checklist_status(&self, claims: &VerifiedClaims, period_id: uuid::Uuid) -> Result<Vec<ChecklistItemResponse>, ClientError> {
        let path = format!("/api/gl/periods/{}/checklist", period_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/gl/periods/{period_id}/checklist`
    pub async fn create_checklist_item(&self, claims: &VerifiedClaims, period_id: uuid::Uuid, body: &CreateChecklistItemRequest) -> Result<ChecklistItemResponse, ClientError> {
        let path = format!("/api/gl/periods/{}/checklist", period_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/gl/periods/{period_id}/checklist/{item_id}/complete`
    pub async fn complete_checklist_item(&self, claims: &VerifiedClaims, period_id: uuid::Uuid, item_id: uuid::Uuid, body: &CompleteChecklistItemRequest) -> Result<ChecklistItemResponse, ClientError> {
        let path = format!("/api/gl/periods/{}/checklist/{}/complete", period_id, item_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/gl/periods/{period_id}/checklist/{item_id}/waive`
    pub async fn waive_checklist_item(&self, claims: &VerifiedClaims, period_id: uuid::Uuid, item_id: uuid::Uuid, body: &WaiveChecklistItemRequest) -> Result<ChecklistItemResponse, ClientError> {
        let path = format!("/api/gl/periods/{}/checklist/{}/waive", period_id, item_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
