//! Generated typed client for the GL Service service.
//!
//! Auto-generated by client-codegen — do not edit.

pub mod types;
pub mod accounts;
pub mod accruals;
pub mod close_checklist;
pub mod exports;
pub mod fx_rates;
pub mod financial_statements;
pub mod gl_detail;
pub mod period_close;
pub mod period_summary;
pub mod reporting_currency;
pub mod revenue_recognition;

pub use types::*;
pub use accounts::AccountsClient;
pub use accruals::AccrualsClient;
pub use close_checklist::CloseChecklistClient;
pub use exports::ExportsClient;
pub use fx_rates::FxRatesClient;
pub use financial_statements::FinancialStatementsClient;
pub use gl_detail::GlDetailClient;
pub use period_close::PeriodCloseClient;
pub use period_summary::PeriodSummaryClient;
pub use reporting_currency::ReportingCurrencyClient;
pub use revenue_recognition::RevenueRecognitionClient;
