//! Client methods for the "Reporting Currency" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_empty};

/// Typed HTTP client for Reporting Currency endpoints.
pub struct ReportingCurrencyClient {
    client: PlatformClient,
}

impl ReportingCurrencyClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/gl/reporting/balance-sheet`
    pub async fn get_reporting_balance_sheet(&self, claims: &VerifiedClaims) -> Result<(), ClientError> {
        let path = format!("/api/gl/reporting/balance-sheet");
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// GET `/api/gl/reporting/income-statement`
    pub async fn get_reporting_income_statement(&self, claims: &VerifiedClaims) -> Result<(), ClientError> {
        let path = format!("/api/gl/reporting/income-statement");
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// GET `/api/gl/reporting/trial-balance`
    pub async fn get_reporting_trial_balance(&self, claims: &VerifiedClaims) -> Result<(), ClientError> {
        let path = format!("/api/gl/reporting/trial-balance");
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
