//! Client methods for the "Revenue Recognition" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response};

/// Typed HTTP client for Revenue Recognition endpoints.
pub struct RevenueRecognitionClient {
    client: PlatformClient,
}

impl RevenueRecognitionClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/gl/revrec/amendments`
    pub async fn amend_contract(&self, claims: &VerifiedClaims, body: &ContractModifiedPayload) -> Result<AmendContractResponse, ClientError> {
        let path = format!("/api/gl/revrec/amendments");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/gl/revrec/contracts`
    pub async fn create_contract(&self, claims: &VerifiedClaims, body: &CreateContractRequest) -> Result<CreateContractResponse, ClientError> {
        let path = format!("/api/gl/revrec/contracts");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/gl/revrec/recognition-runs`
    pub async fn run_recognition_handler(&self, claims: &VerifiedClaims, body: &RecognitionRunRequest) -> Result<RecognitionRunResponse, ClientError> {
        let path = format!("/api/gl/revrec/recognition-runs");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/gl/revrec/schedules`
    pub async fn generate_schedule_handler(&self, claims: &VerifiedClaims, body: &GenerateScheduleRequest) -> Result<GenerateScheduleResponse, ClientError> {
        let path = format!("/api/gl/revrec/schedules");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
