//! Generated typed client for the Platform Client Tenant-Registry Service service.
//!
//! Auto-generated by client-codegen — do not edit.

pub mod types;
pub mod control;
pub mod plans;
pub mod tenants;

pub use types::*;
pub use control::ControlClient;
pub use plans::PlansClient;
pub use tenants::TenantsClient;
pub use tenants::ListTenantsQuery;

// -- PlatformService trait impls (connects to SDK VerticalBuilder) --

impl platform_sdk::PlatformService for ControlClient {
    const SERVICE_NAME: &'static str = "tenant-registry";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for PlansClient {
    const SERVICE_NAME: &'static str = "tenant-registry";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for TenantsClient {
    const SERVICE_NAME: &'static str = "tenant-registry";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

