//! Generated typed client for the Platform Client Tenant-Registry Service service.
//!
//! Auto-generated by client-codegen — do not edit.

pub mod types;
pub mod control;
pub mod plans;
pub mod tenants;

pub use types::*;
pub use control::ControlClient;
pub use plans::PlansClient;
pub use tenants::TenantsClient;
