//! Client methods for the "plans" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{build_query_url, parse_response, ClientError, PlatformClient, VerifiedClaims};

/// Typed HTTP client for plans endpoints.
pub struct PlansClient {
    client: PlatformClient,
}

impl PlansClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/ttp/plans`
    pub async fn list_plans(
        &self,
        claims: &VerifiedClaims,
        status: Option<&str>,
        page: Option<i64>,
        page_size: Option<i64>,
    ) -> Result<PlanListResponse, ClientError> {
        let path = format!("/api/ttp/plans");
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            status: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page: Option<i64>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page_size: Option<i64>,
        }
        let query = Query {
            status: status.map(|s| s.to_string()),
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self
            .client
            .get(&url, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
