//! Client methods for the "tenants" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::types::*;
use platform_sdk::{ClientError, build_query_url, parse_response};
use reqwest::Client;

/// Typed HTTP client for tenants endpoints.
pub struct TenantsClient {
    client: Client,
    base_url: String,
    token: String,
}

impl TenantsClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/tenants`
    pub async fn list_tenants(&self, search: Option<&str>, status: Option<&str>, plan: Option<&str>, app_id: Option<&str>, page: Option<i64>, page_size: Option<i64>) -> Result<TenantListResponse, ClientError> {
        let path = format!("{}/api/tenants", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            search: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            status: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            plan: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            app_id: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page: Option<i64>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page_size: Option<i64>,
        }
        let query = Query {
            search: search.map(|s| s.to_string()),
            status: status.map(|s| s.to_string()),
            plan: plan.map(|s| s.to_string()),
            app_id: app_id.map(|s| s.to_string()),
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/tenants/{tenant_id}`
    pub async fn get_tenant_detail(&self, tenant_id: uuid::Uuid) -> Result<TenantDetailDto, ClientError> {
        let path = format!("{}/api/tenants/{}", self.base_url, tenant_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/tenants/{tenant_id}/app-id`
    pub async fn get_app_id(&self, tenant_id: uuid::Uuid) -> Result<TenantAppIdRow, ClientError> {
        let path = format!("{}/api/tenants/{}/app-id", self.base_url, tenant_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/tenants/{tenant_id}/entitlements`
    pub async fn get_entitlements(&self, tenant_id: uuid::Uuid) -> Result<EntitlementRow, ClientError> {
        let path = format!("{}/api/tenants/{}/entitlements", self.base_url, tenant_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/tenants/{tenant_id}/status`
    pub async fn get_tenant_status(&self, tenant_id: uuid::Uuid) -> Result<TenantStatusRow, ClientError> {
        let path = format!("{}/api/tenants/{}/status", self.base_url, tenant_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
