//! Client methods for the "Password Reset" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{parse_response, ClientError, PlatformClient};

/// Typed HTTP client for Password Reset endpoints.
pub struct PasswordResetClient {
    client: PlatformClient,
}

impl PasswordResetClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/auth/forgot-password`
    pub async fn forgot_password(
        &self,
        body: &ForgotPasswordRequest,
    ) -> Result<GenericOkResponse, ClientError> {
        let path = format!("/api/auth/forgot-password");
        let url = path;
        let resp = self
            .client
            .post_anon(&url, body)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/auth/reset-password`
    pub async fn reset_password(
        &self,
        body: &ResetPasswordRequest,
    ) -> Result<OkResponse, ClientError> {
        let path = format!("/api/auth/reset-password");
        let url = path;
        let resp = self
            .client
            .post_anon(&url, body)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
