/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/health — liveness probe (legacy, kept for compatibility) */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_assets"];
        put?: never;
        post: operations["create_asset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_asset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_asset"];
        trace?: never;
    };
    "/api/maintenance/assets/{asset_id}/calibration-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["record_calibration_event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/assets/{asset_id}/calibration-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_calibration_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/assets/{asset_id}/downtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_asset_downtime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/assets/{asset_id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_readings"];
        put?: never;
        post: operations["record_reading"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_assignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/downtime-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_downtime"];
        put?: never;
        post: operations["create_downtime"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/downtime-events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_downtime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/meter-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_meter_types"];
        put?: never;
        post: operations["create_meter_type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_plans"];
        put?: never;
        post: operations["create_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_plan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["update_plan"];
        trace?: never;
    };
    "/api/maintenance/plans/{plan_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assign_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/work-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_work_orders"];
        put?: never;
        post: operations["create_work_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/work-orders/{wo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_work_order"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/work-orders/{wo_id}/labor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_labor"];
        put?: never;
        post: operations["add_labor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/work-orders/{wo_id}/labor/{labor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["remove_labor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/work-orders/{wo_id}/parts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_parts"];
        put?: never;
        post: operations["add_part"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/work-orders/{wo_id}/parts/{part_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["remove_part"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance/work-orders/{wo_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["transition_work_order"];
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/ready — readiness probe (verifies DB connectivity) */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/version — module identity and schema version */
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddLaborRequest: {
            currency?: string | null;
            description?: string | null;
            hours_decimal: string;
            /** Format: int64 */
            rate_minor: number;
            technician_ref: string;
            tenant_id: string;
        };
        AddPartRequest: {
            currency?: string | null;
            /** Format: uuid */
            inventory_issue_ref?: string | null;
            part_description: string;
            part_ref?: string | null;
            /** Format: int32 */
            quantity: number;
            tenant_id: string;
            /** Format: int64 */
            unit_cost_minor: number;
        };
        /**
         * @description Standard API error envelope.
         *
         *     `error` is a machine-readable code (`not_found`, `validation_error`, etc.).
         *     `message` is human-readable.  `request_id` is populated from the tracing
         *     context already present in request extensions.  `details` carries per-field
         *     errors for 422 responses.
         */
        ApiError: {
            details?: components["schemas"]["FieldError"][] | null;
            error: string;
            message: string;
            request_id?: string | null;
        };
        Asset: {
            asset_tag: string;
            asset_type: components["schemas"]["AssetType"];
            /** Format: date-time */
            created_at: string;
            department?: string | null;
            description?: string | null;
            /** Format: uuid */
            fixed_asset_ref?: string | null;
            /** Format: uuid */
            id: string;
            idempotency_key?: string | null;
            location?: string | null;
            maintenance_schedule?: unknown;
            metadata?: unknown;
            name: string;
            out_of_service: boolean;
            out_of_service_reason?: string | null;
            responsible_person?: string | null;
            serial_number?: string | null;
            status: components["schemas"]["AssetStatus"];
            tenant_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Asset operational status.
         * @enum {string}
         */
        AssetStatus: "active" | "inactive" | "retired";
        /**
         * @description Asset type — classifies what kind of thing is being maintained.
         *     Asset-type agnostic: this is for filtering/reporting, not behavior.
         * @enum {string}
         */
        AssetType: "vehicle" | "machinery" | "equipment" | "facility" | "other";
        AssignPlanRequest: {
            /** Format: uuid */
            asset_id: string;
            tenant_id: string;
        };
        CalibrationEvent: {
            /** Format: uuid */
            asset_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            doc_revision_id?: string | null;
            /** Format: date-time */
            due_at: string;
            /** Format: uuid */
            id: string;
            idempotency_key?: string | null;
            /** Format: date-time */
            performed_at: string;
            result: string;
            tenant_id: string;
        };
        /** @enum {string} */
        CalibrationStatus: "in_cal" | "due" | "overdue" | "out_of_service";
        CalibrationStatusResponse: {
            /** Format: uuid */
            asset_id: string;
            /** Format: date-time */
            last_calibrated_at?: string | null;
            /** Format: date-time */
            next_due_at?: string | null;
            out_of_service: boolean;
            status: components["schemas"]["CalibrationStatus"];
        };
        CreateAssetRequest: {
            asset_tag: string;
            asset_type: string;
            department?: string | null;
            description?: string | null;
            /** Format: uuid */
            fixed_asset_ref?: string | null;
            idempotency_key?: string | null;
            location?: string | null;
            maintenance_schedule?: unknown;
            metadata?: unknown;
            name: string;
            responsible_person?: string | null;
            serial_number?: string | null;
            tenant_id: string;
        };
        CreateDowntimeRequest: {
            /** Format: uuid */
            asset_id?: string | null;
            /** Format: date-time */
            end_time?: string | null;
            idempotency_key?: string | null;
            impact_classification: string;
            notes?: string | null;
            reason: string;
            reason_code?: string | null;
            /** Format: date-time */
            start_time: string;
            tenant_id: string;
            wo_ref?: string | null;
            /** Format: uuid */
            workcenter_id?: string | null;
        };
        CreateMeterTypeRequest: {
            name: string;
            /** Format: int64 */
            rollover_value?: number | null;
            tenant_id: string;
            unit_label: string;
        };
        CreatePlanRequest: {
            asset_type_filter?: string | null;
            /** Format: int32 */
            calendar_interval_days?: number | null;
            description?: string | null;
            /** Format: int64 */
            estimated_cost_minor?: number | null;
            /** Format: int32 */
            estimated_duration_minutes?: number | null;
            /** Format: int64 */
            meter_interval?: number | null;
            /** Format: uuid */
            meter_type_id?: string | null;
            name: string;
            priority?: string | null;
            schedule_type: string;
            task_checklist?: unknown;
            tenant_id: string;
        };
        CreateWorkOrderRequest: {
            /** Format: uuid */
            asset_id: string;
            assigned_to?: string | null;
            checklist?: unknown;
            description?: string | null;
            notes?: string | null;
            /** Format: uuid */
            plan_assignment_id?: string | null;
            priority?: string | null;
            /** Format: date */
            scheduled_date?: string | null;
            tenant_id: string;
            title: string;
            wo_type: string;
        };
        DowntimeEvent: {
            /** Format: uuid */
            asset_id?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            end_time?: string | null;
            /** Format: uuid */
            id: string;
            idempotency_key?: string | null;
            impact_classification: string;
            notes?: string | null;
            reason: string;
            reason_code?: string | null;
            /** Format: date-time */
            start_time: string;
            tenant_id: string;
            wo_ref?: string | null;
            /** Format: uuid */
            workcenter_id?: string | null;
        };
        /** @description A single field-level validation error. */
        FieldError: {
            field: string;
            message: string;
        };
        MaintenancePlan: {
            asset_type_filter?: string | null;
            /** Format: int32 */
            calendar_interval_days?: number | null;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            /** Format: int64 */
            estimated_cost_minor?: number | null;
            /** Format: int32 */
            estimated_duration_minutes?: number | null;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            /** Format: int64 */
            meter_interval?: number | null;
            /** Format: uuid */
            meter_type_id?: string | null;
            name: string;
            priority: components["schemas"]["Priority"];
            schedule_type: components["schemas"]["ScheduleType"];
            task_checklist?: unknown;
            tenant_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        MeterReading: {
            /** Format: uuid */
            asset_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            meter_type_id: string;
            /** Format: int64 */
            reading_value: number;
            /** Format: date-time */
            recorded_at: string;
            recorded_by?: string | null;
            tenant_id: string;
        };
        MeterType: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int64 */
            rollover_value?: number | null;
            tenant_id: string;
            unit_label: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_Asset: {
            data: {
                asset_tag: string;
                asset_type: components["schemas"]["AssetType"];
                /** Format: date-time */
                created_at: string;
                department?: string | null;
                description?: string | null;
                /** Format: uuid */
                fixed_asset_ref?: string | null;
                /** Format: uuid */
                id: string;
                idempotency_key?: string | null;
                location?: string | null;
                maintenance_schedule?: unknown;
                metadata?: unknown;
                name: string;
                out_of_service: boolean;
                out_of_service_reason?: string | null;
                responsible_person?: string | null;
                serial_number?: string | null;
                status: components["schemas"]["AssetStatus"];
                tenant_id: string;
                /** Format: date-time */
                updated_at: string;
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_DowntimeEvent: {
            data: {
                /** Format: uuid */
                asset_id?: string | null;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                end_time?: string | null;
                /** Format: uuid */
                id: string;
                idempotency_key?: string | null;
                impact_classification: string;
                notes?: string | null;
                reason: string;
                reason_code?: string | null;
                /** Format: date-time */
                start_time: string;
                tenant_id: string;
                wo_ref?: string | null;
                /** Format: uuid */
                workcenter_id?: string | null;
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_MaintenancePlan: {
            data: {
                asset_type_filter?: string | null;
                /** Format: int32 */
                calendar_interval_days?: number | null;
                /** Format: date-time */
                created_at: string;
                description?: string | null;
                /** Format: int64 */
                estimated_cost_minor?: number | null;
                /** Format: int32 */
                estimated_duration_minutes?: number | null;
                /** Format: uuid */
                id: string;
                is_active: boolean;
                /** Format: int64 */
                meter_interval?: number | null;
                /** Format: uuid */
                meter_type_id?: string | null;
                name: string;
                priority: components["schemas"]["Priority"];
                schedule_type: components["schemas"]["ScheduleType"];
                task_checklist?: unknown;
                tenant_id: string;
                /** Format: date-time */
                updated_at: string;
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_MeterReading: {
            data: {
                /** Format: uuid */
                asset_id: string;
                /** Format: date-time */
                created_at: string;
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                meter_type_id: string;
                /** Format: int64 */
                reading_value: number;
                /** Format: date-time */
                recorded_at: string;
                recorded_by?: string | null;
                tenant_id: string;
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_MeterType: {
            data: {
                /** Format: date-time */
                created_at: string;
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: int64 */
                rollover_value?: number | null;
                tenant_id: string;
                unit_label: string;
                /** Format: date-time */
                updated_at: string;
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_PlanAssignment: {
            data: {
                /** Format: uuid */
                asset_id: string;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                due_notified_at?: string | null;
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                last_completed_at?: string | null;
                /** Format: int64 */
                last_meter_reading?: number | null;
                /** Format: date */
                next_due_date?: string | null;
                /** Format: int64 */
                next_due_meter?: number | null;
                /** Format: uuid */
                plan_id: string;
                state: string;
                tenant_id: string;
                /** Format: date-time */
                updated_at: string;
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_WoLabor: {
            data: {
                /** Format: date-time */
                created_at: string;
                currency: string;
                description?: string | null;
                hours_decimal: string;
                /** Format: uuid */
                id: string;
                /** Format: int64 */
                rate_minor: number;
                technician_ref: string;
                tenant_id: string;
                /** Format: uuid */
                work_order_id: string;
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_WoPart: {
            data: {
                /** Format: date-time */
                created_at: string;
                currency: string;
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                inventory_issue_ref?: string | null;
                part_description: string;
                part_ref?: string | null;
                /** Format: int32 */
                quantity: number;
                tenant_id: string;
                /** Format: int64 */
                unit_cost_minor: number;
                /** Format: uuid */
                work_order_id: string;
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_WorkOrder: {
            data: {
                /** Format: uuid */
                asset_id: string;
                assigned_to?: string | null;
                checklist?: unknown;
                /** Format: date-time */
                closed_at?: string | null;
                /** Format: date-time */
                completed_at?: string | null;
                /** Format: date-time */
                created_at: string;
                description?: string | null;
                /** Format: int32 */
                downtime_minutes?: number | null;
                /** Format: uuid */
                id: string;
                notes?: string | null;
                /** Format: uuid */
                plan_assignment_id?: string | null;
                priority: components["schemas"]["Priority"];
                /** Format: date */
                scheduled_date?: string | null;
                /** Format: date-time */
                started_at?: string | null;
                status: components["schemas"]["WoStatus"];
                tenant_id: string;
                title: string;
                /** Format: date-time */
                updated_at: string;
                wo_number: string;
                wo_type: components["schemas"]["WoType"];
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** @description Pagination metadata for list endpoints. */
        PaginationMeta: {
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            page_size: number;
            /** Format: int64 */
            total_items: number;
            /** Format: int64 */
            total_pages: number;
        };
        PlanAssignment: {
            /** Format: uuid */
            asset_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            due_notified_at?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            last_completed_at?: string | null;
            /** Format: int64 */
            last_meter_reading?: number | null;
            /** Format: date */
            next_due_date?: string | null;
            /** Format: int64 */
            next_due_meter?: number | null;
            /** Format: uuid */
            plan_id: string;
            state: string;
            tenant_id: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @description Priority level for work orders and maintenance plans.
         * @enum {string}
         */
        Priority: "low" | "medium" | "high" | "critical";
        RecordCalibrationRequest: {
            /** Format: uuid */
            doc_revision_id?: string | null;
            /** Format: date-time */
            due_at: string;
            idempotency_key?: string | null;
            /** Format: date-time */
            performed_at: string;
            result: string;
            tenant_id: string;
        };
        RecordReadingRequest: {
            /** Format: uuid */
            meter_type_id: string;
            /** Format: int64 */
            reading_value: number;
            /** Format: date-time */
            recorded_at?: string | null;
            recorded_by?: string | null;
            tenant_id: string;
        };
        /**
         * @description Schedule type for maintenance plans.
         * @enum {string}
         */
        ScheduleType: "calendar" | "meter" | "both";
        TransitionRequest: {
            /** Format: date-time */
            closed_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: int32 */
            downtime_minutes?: number | null;
            notes?: string | null;
            status: string;
            tenant_id: string;
        };
        UpdateAssetRequest: {
            asset_type?: string | null;
            department?: string | null;
            description?: string | null;
            /** Format: uuid */
            fixed_asset_ref?: string | null;
            location?: string | null;
            maintenance_schedule?: unknown;
            metadata?: unknown;
            name?: string | null;
            out_of_service?: boolean | null;
            out_of_service_reason?: string | null;
            responsible_person?: string | null;
            serial_number?: string | null;
            status?: string | null;
        };
        UpdatePlanRequest: {
            description?: string | null;
            /** Format: int64 */
            estimated_cost_minor?: number | null;
            /** Format: int32 */
            estimated_duration_minutes?: number | null;
            is_active?: boolean | null;
            name?: string | null;
            priority?: string | null;
            task_checklist?: unknown;
        };
        WoLabor: {
            /** Format: date-time */
            created_at: string;
            currency: string;
            description?: string | null;
            hours_decimal: string;
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            rate_minor: number;
            technician_ref: string;
            tenant_id: string;
            /** Format: uuid */
            work_order_id: string;
        };
        WoPart: {
            /** Format: date-time */
            created_at: string;
            currency: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            inventory_issue_ref?: string | null;
            part_description: string;
            part_ref?: string | null;
            /** Format: int32 */
            quantity: number;
            tenant_id: string;
            /** Format: int64 */
            unit_cost_minor: number;
            /** Format: uuid */
            work_order_id: string;
        };
        /**
         * @description Work order status — tracks lifecycle position within the state machine.
         * @enum {string}
         */
        WoStatus: "draft" | "awaiting_approval" | "scheduled" | "in_progress" | "on_hold" | "completed" | "closed" | "cancelled";
        /**
         * @description Work order type — classifies the nature of the maintenance work.
         * @enum {string}
         */
        WoType: "preventive" | "corrective" | "inspection";
        WorkOrder: {
            /** Format: uuid */
            asset_id: string;
            assigned_to?: string | null;
            checklist?: unknown;
            /** Format: date-time */
            closed_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            /** Format: int32 */
            downtime_minutes?: number | null;
            /** Format: uuid */
            id: string;
            notes?: string | null;
            /** Format: uuid */
            plan_assignment_id?: string | null;
            priority: components["schemas"]["Priority"];
            /** Format: date */
            scheduled_date?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            status: components["schemas"]["WoStatus"];
            tenant_id: string;
            title: string;
            /** Format: date-time */
            updated_at: string;
            wo_number: string;
            wo_type: components["schemas"]["WoType"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_assets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_type: string | null;
                status: string | null;
                page: number | null;
                page_size: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of assets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Asset"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_asset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            /** @description Idempotent duplicate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            /** @description Asset created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_asset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asset ID */
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    update_asset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asset ID */
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssetRequest"];
            };
        };
        responses: {
            /** @description Asset updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    record_calibration_event: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asset ID */
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordCalibrationRequest"];
            };
        };
        responses: {
            /** @description Idempotent duplicate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationEvent"];
                };
            };
            /** @description Calibration event recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationEvent"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_calibration_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asset ID */
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current calibration status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationStatusResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_asset_downtime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asset ID */
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Downtime events for asset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DowntimeEvent"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_readings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asset ID */
                asset_id: string;
                meter_type_id: string | null;
                page: number | null;
                page_size: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated meter readings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_MeterReading"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    record_reading: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Asset ID */
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordReadingRequest"];
            };
        };
        responses: {
            /** @description Meter reading recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeterReading"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_assignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string | null;
                asset_id: string | null;
                page: number | null;
                page_size: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated plan assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_PlanAssignment"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_downtime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string | null;
                from: string | null;
                to: string | null;
                page: number | null;
                page_size: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated downtime events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_DowntimeEvent"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_downtime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDowntimeRequest"];
            };
        };
        responses: {
            /** @description Idempotent duplicate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DowntimeEvent"];
                };
            };
            /** @description Downtime event created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DowntimeEvent"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_downtime: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Downtime event ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Downtime event details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DowntimeEvent"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_meter_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of meter types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_MeterType"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_meter_type: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeterTypeRequest"];
            };
        };
        responses: {
            /** @description Meter type created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeterType"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_plans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                is_active: boolean | null;
                page: number | null;
                page_size: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated maintenance plans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_MaintenancePlan"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_plan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            /** @description Plan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenancePlan"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plan ID */
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenancePlan"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    update_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plan ID */
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanRequest"];
            };
        };
        responses: {
            /** @description Plan updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenancePlan"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    assign_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plan ID */
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignPlanRequest"];
            };
        };
        responses: {
            /** @description Plan assigned to asset */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanAssignment"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_work_orders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string | null;
                status: string | null;
                page: number | null;
                page_size: number | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated work orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_WorkOrder"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_work_order: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkOrderRequest"];
            };
        };
        responses: {
            /** @description Work order created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_work_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order ID */
                wo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Work order details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_labor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order ID */
                wo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Labor entries for work order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_WoLabor"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    add_labor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order ID */
                wo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddLaborRequest"];
            };
        };
        responses: {
            /** @description Labor entry added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WoLabor"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    remove_labor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order ID */
                wo_id: string;
                /** @description Labor entry ID */
                labor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Labor entry removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_parts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order ID */
                wo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Parts for work order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_WoPart"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    add_part: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order ID */
                wo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPartRequest"];
            };
        };
        responses: {
            /** @description Part added to work order */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WoPart"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    remove_part: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order ID */
                wo_id: string;
                /** @description Part entry ID */
                part_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Part removed from work order */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    transition_work_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work order ID */
                wo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Work order transitioned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Service is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module version info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
