//! Type definitions for the Maintenance Service client.
//!
//! Auto-generated by client-codegen — do not edit.

#![allow(unused_imports)]

use crate::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Schedule type for maintenance plans.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ScheduleType {
    #[serde(rename = "calendar")]
    Calendar,
    #[serde(rename = "meter")]
    Meter,
    #[serde(rename = "both")]
    Both,
}

impl ScheduleType {
    pub fn as_str(&self) -> &'static str {
        match self {
            ScheduleType::Calendar => "calendar",
            ScheduleType::Meter => "meter",
            ScheduleType::Both => "both",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransitionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub downtime_minutes: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub status: String,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateAssetRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixed_asset_ref: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maintenance_schedule: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub out_of_service: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub out_of_service_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub responsible_person: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdatePlanRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_cost_minor: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_duration_minutes: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_checklist: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WoLabor {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub hours_decimal: String,
    pub id: uuid::Uuid,
    pub rate_minor: i64,
    pub technician_ref: String,
    pub tenant_id: String,
    pub work_order_id: uuid::Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WoPart {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub currency: String,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inventory_issue_ref: Option<uuid::Uuid>,
    pub part_description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_ref: Option<String>,
    pub quantity: i32,
    pub tenant_id: String,
    pub unit_cost_minor: i64,
    pub work_order_id: uuid::Uuid,
}

/// Work order status — tracks lifecycle position within the state machine.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum WoStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "awaiting_approval")]
    AwaitingApproval,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "on_hold")]
    OnHold,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "closed")]
    Closed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

impl WoStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            WoStatus::Draft => "draft",
            WoStatus::AwaitingApproval => "awaiting_approval",
            WoStatus::Scheduled => "scheduled",
            WoStatus::InProgress => "in_progress",
            WoStatus::OnHold => "on_hold",
            WoStatus::Completed => "completed",
            WoStatus::Closed => "closed",
            WoStatus::Cancelled => "cancelled",
        }
    }
}

/// Work order type — classifies the nature of the maintenance work.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum WoType {
    #[serde(rename = "preventive")]
    Preventive,
    #[serde(rename = "corrective")]
    Corrective,
    #[serde(rename = "inspection")]
    Inspection,
}

impl WoType {
    pub fn as_str(&self) -> &'static str {
        match self {
            WoType::Preventive => "preventive",
            WoType::Corrective => "corrective",
            WoType::Inspection => "inspection",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkOrder {
    pub asset_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assigned_to: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checklist: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<chrono::DateTime<chrono::Utc>>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub downtime_minutes: Option<i32>,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_assignment_id: Option<uuid::Uuid>,
    pub priority: Priority,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_date: Option<chrono::NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::Utc>>,
    pub status: WoStatus,
    pub tenant_id: String,
    pub title: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub wo_number: String,
    pub wo_type: WoType,
}
