//! Type definitions for the Maintenance Service client.
//!
//! Auto-generated by client-codegen — do not edit.

#![allow(unused_imports)]

use crate::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Pagination metadata for list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginationMeta {
    pub page: i64,
    pub page_size: i64,
    pub total_items: i64,
    pub total_pages: i64,
}

/// Generic paginated response envelope.
///
/// Local definition without `ToSchema` bound — client crates don't need
/// OpenAPI schema derivation. Wire-compatible with `platform_http_contracts::PaginatedResponse`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedResponse<T> {
    pub data: Vec<T>,
    pub pagination: PaginationMeta,
}

/// Simple wrapper for sub-collection list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataResponse<T> {
    pub data: Vec<T>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AddLaborRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub hours_decimal: String,
    pub rate_minor: i64,
    pub technician_ref: String,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AddPartRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inventory_issue_ref: Option<uuid::Uuid>,
    pub part_description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub part_ref: Option<String>,
    pub quantity: i32,
    pub tenant_id: String,
    pub unit_cost_minor: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Asset {
    pub asset_tag: String,
    pub asset_type: AssetType,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixed_asset_ref: Option<uuid::Uuid>,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maintenance_schedule: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub name: String,
    pub out_of_service: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub out_of_service_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub responsible_person: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    pub status: AssetStatus,
    pub tenant_id: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

/// Asset operational status.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum AssetStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "retired")]
    Retired,
}

impl AssetStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            AssetStatus::Active => "active",
            AssetStatus::Inactive => "inactive",
            AssetStatus::Retired => "retired",
        }
    }
}

/// Asset type — classifies what kind of thing is being maintained.
/// Asset-type agnostic: this is for filtering/reporting, not behavior.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum AssetType {
    #[serde(rename = "vehicle")]
    Vehicle,
    #[serde(rename = "machinery")]
    Machinery,
    #[serde(rename = "equipment")]
    Equipment,
    #[serde(rename = "facility")]
    Facility,
    #[serde(rename = "other")]
    Other,
}

impl AssetType {
    pub fn as_str(&self) -> &'static str {
        match self {
            AssetType::Vehicle => "vehicle",
            AssetType::Machinery => "machinery",
            AssetType::Equipment => "equipment",
            AssetType::Facility => "facility",
            AssetType::Other => "other",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssignPlanRequest {
    pub asset_id: uuid::Uuid,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalibrationEvent {
    pub asset_id: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub doc_revision_id: Option<uuid::Uuid>,
    pub due_at: chrono::DateTime<chrono::Utc>,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    pub performed_at: chrono::DateTime<chrono::Utc>,
    pub result: String,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum CalibrationStatus {
    #[serde(rename = "in_cal")]
    InCal,
    #[serde(rename = "due")]
    Due,
    #[serde(rename = "overdue")]
    Overdue,
    #[serde(rename = "out_of_service")]
    OutOfService,
}

impl CalibrationStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            CalibrationStatus::InCal => "in_cal",
            CalibrationStatus::Due => "due",
            CalibrationStatus::Overdue => "overdue",
            CalibrationStatus::OutOfService => "out_of_service",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CalibrationStatusResponse {
    pub asset_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_calibrated_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_due_at: Option<chrono::DateTime<chrono::Utc>>,
    pub out_of_service: bool,
    pub status: CalibrationStatus,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateAssetRequest {
    pub asset_tag: String,
    pub asset_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixed_asset_ref: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maintenance_schedule: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub responsible_person: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub serial_number: Option<String>,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateDowntimeRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_time: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    pub impact_classification: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
    pub start_time: chrono::DateTime<chrono::Utc>,
    pub tenant_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wo_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workcenter_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateMeterTypeRequest {
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rollover_value: Option<i64>,
    pub tenant_id: String,
    pub unit_label: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreatePlanRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_type_filter: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub calendar_interval_days: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_cost_minor: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_duration_minutes: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meter_interval: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meter_type_id: Option<uuid::Uuid>,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<String>,
    pub schedule_type: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_checklist: Option<serde_json::Value>,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateWorkOrderRequest {
    pub asset_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assigned_to: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checklist: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plan_assignment_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_date: Option<chrono::NaiveDate>,
    pub tenant_id: String,
    pub title: String,
    pub wo_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DowntimeEvent {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_id: Option<uuid::Uuid>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_time: Option<chrono::DateTime<chrono::Utc>>,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    pub impact_classification: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
    pub start_time: chrono::DateTime<chrono::Utc>,
    pub tenant_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wo_ref: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workcenter_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MaintenancePlan {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub asset_type_filter: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub calendar_interval_days: Option<i32>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_cost_minor: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub estimated_duration_minutes: Option<i32>,
    pub id: uuid::Uuid,
    pub is_active: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meter_interval: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub meter_type_id: Option<uuid::Uuid>,
    pub name: String,
    pub priority: Priority,
    pub schedule_type: ScheduleType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_checklist: Option<serde_json::Value>,
    pub tenant_id: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MeterReading {
    pub asset_id: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: uuid::Uuid,
    pub meter_type_id: uuid::Uuid,
    pub reading_value: i64,
    pub recorded_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recorded_by: Option<String>,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MeterType {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: uuid::Uuid,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rollover_value: Option<i64>,
    pub tenant_id: String,
    pub unit_label: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanAssignment {
    pub asset_id: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_notified_at: Option<chrono::DateTime<chrono::Utc>>,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_completed_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_meter_reading: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_due_date: Option<chrono::NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_due_meter: Option<i64>,
    pub plan_id: uuid::Uuid,
    pub state: String,
    pub tenant_id: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

/// Priority level for work orders and maintenance plans.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum Priority {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "critical")]
    Critical,
}

impl Priority {
    pub fn as_str(&self) -> &'static str {
        match self {
            Priority::Low => "low",
            Priority::Medium => "medium",
            Priority::High => "high",
            Priority::Critical => "critical",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecordCalibrationRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub doc_revision_id: Option<uuid::Uuid>,
    pub due_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    pub performed_at: chrono::DateTime<chrono::Utc>,
    pub result: String,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecordReadingRequest {
    pub meter_type_id: uuid::Uuid,
    pub reading_value: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recorded_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recorded_by: Option<String>,
    pub tenant_id: String,
}
