//! Client methods for the "Time Entries" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{parse_response, ClientError, PlatformClient, VerifiedClaims};

/// Typed HTTP client for Time Entries endpoints.
pub struct TimeEntriesClient {
    client: PlatformClient,
}

impl TimeEntriesClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/production/time-entries/manual`
    pub async fn manual_entry(
        &self,
        claims: &VerifiedClaims,
        body: &ManualEntryRequest,
    ) -> Result<TimeEntry, ClientError> {
        let path = format!("/api/production/time-entries/manual");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/production/time-entries/start`
    pub async fn start_timer(
        &self,
        claims: &VerifiedClaims,
        body: &StartTimerRequest,
    ) -> Result<TimeEntry, ClientError> {
        let path = format!("/api/production/time-entries/start");
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/production/time-entries/{id}/stop`
    pub async fn stop_timer(
        &self,
        claims: &VerifiedClaims,
        id: uuid::Uuid,
        body: &StopTimerRequest,
    ) -> Result<TimeEntry, ClientError> {
        let path = format!("/api/production/time-entries/{}/stop", id);
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/production/work-orders/{id}/time-entries`
    pub async fn list_time_entries(
        &self,
        claims: &VerifiedClaims,
        id: uuid::Uuid,
    ) -> Result<PaginatedResponse<TimeEntry>, ClientError> {
        let path = format!("/api/production/work-orders/{}/time-entries", id);
        let url = path;
        let resp = self
            .client
            .get(&url, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
