//! Client methods for the "Workcenters" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, build_query_url, parse_response};

/// Typed HTTP client for Workcenters endpoints.
pub struct WorkcentersClient {
    client: PlatformClient,
}

impl WorkcentersClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/production/workcenters`
    pub async fn list_workcenters(&self, claims: &VerifiedClaims, page: Option<i64>, page_size: Option<i64>) -> Result<PaginatedResponse<Workcenter>, ClientError> {
        let path = format!("/api/production/workcenters");
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            page: Option<i64>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page_size: Option<i64>,
        }
        let query = Query {
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/production/workcenters`
    pub async fn create_workcenter(&self, claims: &VerifiedClaims, body: &CreateWorkcenterRequest) -> Result<Workcenter, ClientError> {
        let path = format!("/api/production/workcenters");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/production/workcenters/{id}`
    pub async fn get_workcenter(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<Workcenter, ClientError> {
        let path = format!("/api/production/workcenters/{}", id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/production/workcenters/{id}`
    pub async fn update_workcenter(&self, claims: &VerifiedClaims, id: uuid::Uuid, body: &UpdateWorkcenterRequest) -> Result<Workcenter, ClientError> {
        let path = format!("/api/production/workcenters/{}", id);
        let url = path;
        let resp = self.client.put(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/production/workcenters/{id}/deactivate`
    pub async fn deactivate_workcenter(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<Workcenter, ClientError> {
        let path = format!("/api/production/workcenters/{}/deactivate", id);
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
