//! Client methods for the "DLQ" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response};

/// Typed HTTP client for DLQ endpoints.
pub struct DlqClient {
    client: PlatformClient,
}

impl DlqClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/dlq`
    pub async fn list_dlq(&self, claims: &VerifiedClaims) -> Result<DlqListResponse, ClientError> {
        let path = format!("/api/dlq");
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/dlq/{id}`
    pub async fn get_dlq_item(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<DlqDetailResponse, ClientError> {
        let path = format!("/api/dlq/{}", id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/dlq/{id}/abandon`
    pub async fn abandon_dlq_item(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<DlqActionResponse, ClientError> {
        let path = format!("/api/dlq/{}/abandon", id);
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/dlq/{id}/replay`
    pub async fn replay_dlq_item(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<DlqActionResponse, ClientError> {
        let path = format!("/api/dlq/{}/replay", id);
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
