//! Emit client structs with methods for each tag group.

use crate::spec::{Endpoint, HttpMethod, ParsedSpec, Param, ResponseKind};

/// Methods with this many query params or more get a public query struct
/// instead of individual parameters.
pub const QUERY_STRUCT_THRESHOLD: usize = 5;

pub fn emit(parsed: &ParsedSpec, tag: &str, indices: &[usize]) -> String {
    let struct_name = tag_to_client_name(tag);
    // Determine which imports are needed
    let eps: Vec<&Endpoint> = indices.iter().map(|&i| &parsed.endpoints[i]).collect();
    let needs_types = eps.iter().any(|ep| {
        ep.request_body.is_some()
            || matches!(&ep.response, ResponseKind::Json(_))
    });
    let needs_query = eps.iter().any(|ep| !ep.query_params.is_empty());
    let needs_parse_response = eps.iter().any(|ep| matches!(&ep.response, ResponseKind::Json(_)));
    let needs_parse_empty = eps.iter().any(|ep| matches!(&ep.response, ResponseKind::Empty));

    let mut out = String::with_capacity(2048);
    out.push_str(&format!(
        "//! Client methods for the \"{tag}\" endpoints.\n"
    ));
    out.push_str("//!\n//! Auto-generated by client-codegen — do not edit.\n\n");
    if needs_types {
        out.push_str("use crate::*;\n");
    }

    // Build selective platform_sdk import
    let mut sdk_imports = vec!["ClientError", "PlatformClient", "VerifiedClaims"];
    if needs_query {
        sdk_imports.push("build_query_url");
    }
    if needs_parse_response {
        sdk_imports.push("parse_response");
    }
    if needs_parse_empty {
        sdk_imports.push("parse_empty");
    }
    out.push_str(&format!(
        "use platform_sdk::{{{}}};\n\n",
        sdk_imports.join(", ")
    ));

    // Emit public query structs for methods with many query params
    for &idx in indices {
        let ep = &parsed.endpoints[idx];
        if ep.query_params.len() >= QUERY_STRUCT_THRESHOLD {
            emit_public_query_struct(&mut out, ep);
        }
    }

    // Client struct — wraps PlatformClient which handles headers, retry, and auth
    out.push_str(&format!("/// Typed HTTP client for {tag} endpoints.\n"));
    out.push_str(&format!("pub struct {struct_name} {{\n"));
    out.push_str("    client: PlatformClient,\n");
    out.push_str("}\n\n");

    // Constructor
    out.push_str(&format!("impl {struct_name} {{\n"));
    out.push_str("    pub fn new(client: PlatformClient) -> Self {\n");
    out.push_str("        Self { client }\n");
    out.push_str("    }\n");

    // Methods
    for &idx in indices {
        let ep = &parsed.endpoints[idx];
        out.push('\n');
        emit_method(&mut out, ep);
    }

    out.push_str("}\n");
    out
}

fn emit_method(out: &mut String, ep: &Endpoint) {
    let fn_name = &ep.operation_id;
    let return_type = match &ep.response {
        ResponseKind::Json(t) => format!("Result<{t}, ClientError>"),
        ResponseKind::Empty => "Result<(), ClientError>".to_string(),
    };

    // Build parameter list — claims is always first after &self
    let mut params = vec!["claims: &VerifiedClaims".to_string()];
    for p in &ep.path_params {
        params.push(format!("{}: {}", sanitize_param(&p.name), param_arg_type(&p.rust_type)));
    }
    let use_public_query = ep.query_params.len() >= QUERY_STRUCT_THRESHOLD;
    if use_public_query {
        let query_struct = op_id_to_query_struct(&ep.operation_id);
        params.push(format!("query: &{query_struct}"));
    } else {
        for p in &ep.query_params {
            let ty = if p.required {
                param_arg_type(&p.rust_type)
            } else {
                format!("Option<{}>", param_arg_type(&p.rust_type))
            };
            params.push(format!("{}: {ty}", sanitize_param(&p.name)));
        }
    }
    // Request body
    if let Some(body_type) = &ep.request_body {
        params.push(format!("body: &{body_type}"));
    }

    let params_str = format!("&self, {}", params.join(", "));

    // Method signature
    let method_name = match ep.method {
        HttpMethod::Get => "GET",
        HttpMethod::Post => "POST",
        HttpMethod::Put => "PUT",
        HttpMethod::Patch => "PATCH",
        HttpMethod::Delete => "DELETE",
    };

    out.push_str(&format!(
        "    /// {method_name} `{path}`\n",
        path = ep.path
    ));
    out.push_str(&format!(
        "    pub async fn {fn_name}({params_str}) -> {return_type} {{\n"
    ));

    // Build URL with path params substituted
    let url_expr = build_url_expr(&ep.path, &ep.path_params);
    out.push_str(&format!("        let path = {url_expr};\n"));

    // Query params
    let has_query = !ep.query_params.is_empty();
    if has_query {
        if use_public_query {
            // query is already passed as a parameter — use it directly
            out.push_str("        let url = build_query_url(&path, query)?;\n");
        } else {
            emit_inline_query_struct(out, &ep.query_params);
            out.push_str("        let url = build_query_url(&path, &query)?;\n");
        }
    } else {
        out.push_str("        let url = path;\n");
    }

    // Build request via PlatformClient (handles headers, retry, auth)
    match ep.method {
        HttpMethod::Get => {
            out.push_str("        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;\n");
        }
        HttpMethod::Delete => {
            out.push_str("        let resp = self.client.delete(&url, claims).await.map_err(ClientError::Network)?;\n");
        }
        HttpMethod::Post => {
            if ep.request_body.is_some() {
                out.push_str("        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;\n");
            } else {
                out.push_str("        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;\n");
            }
        }
        HttpMethod::Put => {
            if ep.request_body.is_some() {
                out.push_str("        let resp = self.client.put(&url, body, claims).await.map_err(ClientError::Network)?;\n");
            } else {
                out.push_str("        let resp = self.client.put(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;\n");
            }
        }
        HttpMethod::Patch => {
            if ep.request_body.is_some() {
                out.push_str("        let resp = self.client.patch(&url, body, claims).await.map_err(ClientError::Network)?;\n");
            } else {
                out.push_str("        let resp = self.client.patch(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;\n");
            }
        }
    }

    // Parse response
    match &ep.response {
        ResponseKind::Json(_) => {
            out.push_str("        parse_response(resp).await\n");
        }
        ResponseKind::Empty => {
            out.push_str("        parse_empty(resp).await\n");
        }
    }

    out.push_str("    }\n");
}

fn emit_inline_query_struct(out: &mut String, params: &[Param]) {
    out.push_str("        #[derive(serde::Serialize)]\n");
    out.push_str("        struct Query {\n");
    for p in params {
        // Query structs use owned types to avoid lifetime issues
        let owned_type = query_owned_type(&p.rust_type);
        if !p.required {
            out.push_str(
                "            #[serde(skip_serializing_if = \"Option::is_none\")]\n",
            );
            out.push_str(&format!(
                "            {}: Option<{owned_type}>,\n",
                sanitize_param(&p.name),
            ));
        } else {
            out.push_str(&format!(
                "            {}: {owned_type},\n",
                sanitize_param(&p.name),
            ));
        }
    }
    out.push_str("        }\n");
    out.push_str("        let query = Query {\n");
    for p in params {
        let name = sanitize_param(&p.name);
        // Convert &str args to String for the owned struct
        if p.rust_type == "String" {
            if p.required {
                out.push_str(&format!("            {name}: {name}.to_string(),\n"));
            } else {
                out.push_str(&format!(
                    "            {name}: {name}.map(|s| s.to_string()),\n"
                ));
            }
        } else {
            out.push_str(&format!("            {name},\n"));
        }
    }
    out.push_str("        };\n");
}

/// Return the owned version of a type for query structs.
fn query_owned_type(rust_type: &str) -> String {
    match rust_type {
        "String" => "String".to_string(),
        t => t.to_string(),
    }
}

fn build_url_expr(path: &str, path_params: &[Param]) -> String {
    // PlatformClient prepends base_url — only emit the path portion
    if path_params.is_empty() {
        return format!("format!(\"{path}\")");
    }
    let mut fmt_path = path.to_string();
    let mut format_args = Vec::new();
    for p in path_params {
        let placeholder = format!("{{{}}}", p.name);
        fmt_path = fmt_path.replace(&placeholder, "{}");
        format_args.push(sanitize_param(&p.name));
    }
    let args = format_args.join(", ");
    format!("format!(\"{fmt_path}\", {args})")
}

fn param_arg_type(rust_type: &str) -> String {
    match rust_type {
        "String" => "&str".to_string(),
        t if t.starts_with("Option<") => t.to_string(),
        t => t.to_string(),
    }
}

fn sanitize_param(name: &str) -> String {
    let s = name.replace('-', "_");
    match s.as_str() {
        "type" | "move" | "ref" | "self" | "super" | "crate" | "mod" | "fn" | "let" | "mut"
        | "pub" | "use" | "as" | "in" | "for" | "if" | "else" | "loop" | "while" | "match"
        | "return" | "break" | "continue" | "struct" | "enum" | "impl" | "trait" | "where"
        | "async" | "await" | "dyn" | "static" | "const" | "extern" | "unsafe" => {
            format!("r#{s}")
        }
        _ => s,
    }
}

/// Emit a public query struct for methods with many query params.
/// Placed at module level so callers can construct and pass it.
fn emit_public_query_struct(out: &mut String, ep: &Endpoint) {
    let struct_name = op_id_to_query_struct(&ep.operation_id);
    out.push_str(&format!("/// Query parameters for [`{}`].\n", ep.operation_id));
    out.push_str("#[derive(Debug, Clone, Default, serde::Serialize)]\n");
    out.push_str(&format!("pub struct {struct_name} {{\n"));
    for p in &ep.query_params {
        let owned_type = query_owned_type(&p.rust_type);
        if !p.required {
            out.push_str(
                "    #[serde(skip_serializing_if = \"Option::is_none\")]\n",
            );
            out.push_str(&format!(
                "    pub {}: Option<{owned_type}>,\n",
                sanitize_param(&p.name),
            ));
        } else {
            out.push_str(&format!(
                "    pub {}: {owned_type},\n",
                sanitize_param(&p.name),
            ));
        }
    }
    out.push_str("}\n\n");
}

/// Convert an operation_id like "search_parties" to "SearchPartiesQuery".
pub fn op_id_to_query_struct(operation_id: &str) -> String {
    let pascal: String = operation_id
        .split('_')
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect();
    format!("{pascal}Query")
}

fn tag_to_client_name(tag: &str) -> String {
    let pascal: String = tag
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + &c.as_str().to_lowercase(),
            }
        })
        .collect();
    format!("{pascal}Client")
}
