//! Client methods for the "Refs" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use platform_sdk::{ClientError, parse_empty};
use reqwest::Client;

/// Typed HTTP client for Refs endpoints.
pub struct RefsClient {
    client: Client,
    base_url: String,
    token: String,
}

impl RefsClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/shipping-receiving/po-lines/{po_line_id}/lines`
    pub async fn lines_by_po_line(&self, po_line_id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("{}/api/shipping-receiving/po-lines/{}/lines", self.base_url, po_line_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// GET `/api/shipping-receiving/po/{po_id}/shipments`
    pub async fn shipments_by_po(&self, po_id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("{}/api/shipping-receiving/po/{}/shipments", self.base_url, po_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// GET `/api/shipping-receiving/source/{ref_type}/{ref_id}/shipments`
    pub async fn shipments_by_source_ref(&self, ref_type: &str, ref_id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("{}/api/shipping-receiving/source/{}/{}/shipments", self.base_url, ref_type, ref_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
