/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/shipping-receiving/po-lines/{po_line_id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lines_by_po_line"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/po/{po_id}/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["shipments_by_po"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_shipments"];
        put?: never;
        post: operations["create_shipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_shipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["close_shipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deliver_shipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add_line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{id}/routings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_routings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{id}/ship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ship_shipment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["transition_status"];
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{shipment_id}/lines/{line_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["accept_line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{shipment_id}/lines/{line_id}/receive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receive_line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{shipment_id}/lines/{line_id}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["route_line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/shipments/{shipment_id}/lines/{line_id}/ship-qty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ship_line_qty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipping-receiving/source/{ref_type}/{ref_id}/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["shipments_by_source_ref"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddLineRequest: {
            /** Format: uuid */
            po_id?: string | null;
            /** Format: uuid */
            po_line_id?: string | null;
            /** Format: int64 */
            qty_expected: number;
            sku?: string | null;
            /** Format: uuid */
            source_ref_id?: string | null;
            source_ref_type?: string | null;
            uom?: string | null;
            /** Format: uuid */
            warehouse_id?: string | null;
        };
        /**
         * @description Standard API error envelope.
         *
         *     `error` is a machine-readable code (`not_found`, `validation_error`, etc.).
         *     `message` is human-readable.  `request_id` is populated from the tracing
         *     context already present in request extensions.  `details` carries per-field
         *     errors for 422 responses.
         */
        ApiError: {
            details?: components["schemas"]["FieldError"][] | null;
            error: string;
            message: string;
            request_id?: string | null;
        };
        CreateShipmentRequest: {
            /** Format: uuid */
            carrier_party_id?: string | null;
            currency?: string | null;
            direction: components["schemas"]["Direction"];
            /** Format: date-time */
            expected_arrival_date?: string | null;
            /** Format: int64 */
            freight_cost_minor?: number | null;
            tracking_number?: string | null;
        };
        /**
         * @description Shipment direction — determines which state machine applies.
         * @enum {string}
         */
        Direction: "inbound" | "outbound";
        /** @description A single field-level validation error. */
        FieldError: {
            field: string;
            message: string;
        };
        /** @description Row returned from inspection_routings table. */
        InspectionRoutingRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            idempotency_key?: string | null;
            reason?: string | null;
            route_decision: string;
            /** Format: date-time */
            routed_at: string;
            /** Format: uuid */
            routed_by?: string | null;
            /** Format: uuid */
            shipment_id: string;
            /** Format: uuid */
            shipment_line_id: string;
            /** Format: uuid */
            tenant_id: string;
        };
        /**
         * @description Generic paginated response envelope.
         *
         *     Every list endpoint returns this wrapper so consumers get consistent
         *     pagination metadata regardless of the underlying entity type.
         */
        PaginatedResponse_Shipment: {
            data: {
                /** Format: date-time */
                arrived_at?: string | null;
                /** Format: uuid */
                carrier_party_id?: string | null;
                /** Format: date-time */
                closed_at?: string | null;
                /** Format: date-time */
                created_at: string;
                /** Format: uuid */
                created_by?: string | null;
                currency?: string | null;
                /** Format: date-time */
                delivered_at?: string | null;
                direction: components["schemas"]["Direction"];
                /** Format: date-time */
                expected_arrival_date?: string | null;
                /** Format: int64 */
                freight_cost_minor?: number | null;
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                shipped_at?: string | null;
                status: string;
                /** Format: uuid */
                tenant_id: string;
                tracking_number?: string | null;
                /** Format: date-time */
                updated_at: string;
            }[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** @description Pagination metadata for list endpoints. */
        PaginationMeta: {
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            page_size: number;
            /** Format: int64 */
            total_items: number;
            /** Format: int64 */
            total_pages: number;
        };
        ReceiveLineRequest: {
            /** Format: int64 */
            qty_accepted: number;
            /** Format: int64 */
            qty_received: number;
            /** Format: int64 */
            qty_rejected: number;
        };
        /** @description Request to route a shipment line. */
        RouteLineRequest: {
            idempotency_key?: string | null;
            reason?: string | null;
            route_decision: string;
        };
        ShipLineQtyRequest: {
            /** Format: int64 */
            qty_shipped: number;
        };
        Shipment: {
            /** Format: date-time */
            arrived_at?: string | null;
            /** Format: uuid */
            carrier_party_id?: string | null;
            /** Format: date-time */
            closed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            created_by?: string | null;
            currency?: string | null;
            /** Format: date-time */
            delivered_at?: string | null;
            direction: components["schemas"]["Direction"];
            /** Format: date-time */
            expected_arrival_date?: string | null;
            /** Format: int64 */
            freight_cost_minor?: number | null;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            shipped_at?: string | null;
            status: string;
            /** Format: uuid */
            tenant_id: string;
            tracking_number?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        ShipmentLineRow: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            inventory_ref_id?: string | null;
            /** Format: uuid */
            po_id?: string | null;
            /** Format: uuid */
            po_line_id?: string | null;
            /** Format: int64 */
            qty_accepted: number;
            /** Format: int64 */
            qty_expected: number;
            /** Format: int64 */
            qty_received: number;
            /** Format: int64 */
            qty_rejected: number;
            /** Format: int64 */
            qty_shipped: number;
            /** Format: uuid */
            shipment_id: string;
            sku?: string | null;
            /** Format: uuid */
            source_ref_id?: string | null;
            source_ref_type?: string | null;
            /** Format: uuid */
            tenant_id: string;
            uom?: string | null;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            warehouse_id?: string | null;
        };
        TransitionStatusRequest: {
            /** Format: date-time */
            arrived_at?: string | null;
            /** Format: date-time */
            closed_at?: string | null;
            /** Format: date-time */
            delivered_at?: string | null;
            /** Format: date-time */
            shipped_at?: string | null;
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    lines_by_po_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description PO line ID */
                po_line_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lines for PO line */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentLineRow"][];
                };
            };
        };
    };
    shipments_by_po: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Purchase order ID */
                po_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shipments for PO */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"][];
                };
            };
        };
    };
    list_shipments: {
        parameters: {
            query?: {
                direction?: string;
                status?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated shipments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Shipment"];
                };
            };
        };
    };
    create_shipment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShipmentRequest"];
            };
        };
        responses: {
            /** @description Shipment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_shipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shipment details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    close_shipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shipment closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
            /** @description Invalid transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deliver_shipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shipment delivered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
            /** @description Invalid transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    add_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddLineRequest"];
            };
        };
        responses: {
            /** @description Line added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentLineRow"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Shipment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_routings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Routings for shipment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionRoutingRow"][];
                };
            };
        };
    };
    ship_shipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shipment shipped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
            /** @description Invalid transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    transition_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionStatusRequest"];
            };
        };
        responses: {
            /** @description Shipment after transition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
            /** @description Invalid transition or guard failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    accept_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                shipment_id: string;
                /** @description Shipment line ID */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Line accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentLineRow"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    receive_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                shipment_id: string;
                /** @description Shipment line ID */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiveLineRequest"];
            };
        };
        responses: {
            /** @description Line received */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentLineRow"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    route_line: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                shipment_id: string;
                /** @description Shipment line ID */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteLineRequest"];
            };
        };
        responses: {
            /** @description Line routed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionRoutingRow"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Already routed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    ship_line_qty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Shipment ID */
                shipment_id: string;
                /** @description Shipment line ID */
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShipLineQtyRequest"];
            };
        };
        responses: {
            /** @description Shipped quantity set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentLineRow"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    shipments_by_source_ref: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source reference type */
                ref_type: string;
                /** @description Source reference ID */
                ref_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shipments by source ref */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"][];
                };
            };
        };
    };
}
