//! Client methods for the "Aging" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, build_query_url, parse_response, parse_empty};
use reqwest::Client;

/// Typed HTTP client for Aging endpoints.
pub struct AgingClient {
    client: Client,
    base_url: String,
    token: String,
}

impl AgingClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/ar/aging`
    pub async fn get_aging(&self, customer_id: Option<i32>) -> Result<(), ClientError> {
        let path = format!("{}/api/ar/aging", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            customer_id: Option<i32>,
        }
        let query = Query {
            customer_id,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// POST `/api/ar/aging/refresh`
    pub async fn refresh_aging(&self, body: &RefreshAgingRequest) -> Result<AgingSnapshot, ClientError> {
        let path = format!("{}/api/ar/aging/refresh", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
