//! Client methods for the "Allocation" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, parse_response};
use reqwest::Client;

/// Typed HTTP client for Allocation endpoints.
pub struct AllocationClient {
    client: Client,
    base_url: String,
    token: String,
}

impl AllocationClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// POST `/api/ar/payments/allocate`
    pub async fn allocate_payment(&self, body: &AllocatePaymentRequest) -> Result<AllocationResult, ClientError> {
        let path = format!("{}/api/ar/payments/allocate", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
