//! Client methods for the "Charges" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, build_query_url, parse_response};

/// Typed HTTP client for Charges endpoints.
pub struct ChargesClient {
    client: PlatformClient,
}

impl ChargesClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/ar/charges`
    pub async fn list_charges(&self, claims: &VerifiedClaims, customer_id: Option<i32>, invoice_id: Option<i32>, status: Option<String>, limit: Option<i32>, offset: Option<i32>) -> Result<PaginatedResponse<Charge>, ClientError> {
        let path = format!("/api/ar/charges");
        #[derive(serde::Serialize)]
        struct Query {
            customer_id: Option<i32>,
            invoice_id: Option<i32>,
            status: Option<String>,
            limit: Option<i32>,
            offset: Option<i32>,
        }
        let query = Query {
            customer_id,
            invoice_id,
            status,
            limit,
            offset,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ar/charges`
    pub async fn create_charge(&self, claims: &VerifiedClaims, body: &CreateChargeRequest) -> Result<Charge, ClientError> {
        let path = format!("/api/ar/charges");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/ar/charges/{id}`
    pub async fn get_charge(&self, claims: &VerifiedClaims, id: i32) -> Result<Charge, ClientError> {
        let path = format!("/api/ar/charges/{}", id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ar/charges/{id}/capture`
    pub async fn capture_charge(&self, claims: &VerifiedClaims, id: i32, body: &CaptureChargeRequest) -> Result<Charge, ClientError> {
        let path = format!("/api/ar/charges/{}/capture", id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
