//! Client methods for the "Customers" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, build_query_url, parse_response, parse_empty};
use reqwest::Client;

/// Typed HTTP client for Customers endpoints.
pub struct CustomersClient {
    client: Client,
    base_url: String,
    token: String,
}

impl CustomersClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/ar/customers`
    pub async fn list_customers(&self, external_customer_id: Option<&str>, limit: Option<i32>, offset: Option<i32>) -> Result<(), ClientError> {
        let path = format!("{}/api/ar/customers", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            external_customer_id: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            limit: Option<i32>,
            #[serde(skip_serializing_if = "Option::is_none")]
            offset: Option<i32>,
        }
        let query = Query {
            external_customer_id: external_customer_id.map(|s| s.to_string()),
            limit,
            offset,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// POST `/api/ar/customers`
    pub async fn create_customer(&self, body: &CreateCustomerRequest) -> Result<Customer, ClientError> {
        let path = format!("{}/api/ar/customers", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/ar/customers/{id}`
    pub async fn get_customer(&self, id: i32) -> Result<Customer, ClientError> {
        let path = format!("{}/api/ar/customers/{}", self.base_url, id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/ar/customers/{id}`
    pub async fn update_customer(&self, id: i32, body: &UpdateCustomerRequest) -> Result<Customer, ClientError> {
        let path = format!("{}/api/ar/customers/{}", self.base_url, id);
        let url = path;
        let resp = self.client.put(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
