//! Client methods for the "Dunning" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response};

/// Typed HTTP client for Dunning endpoints.
pub struct DunningClient {
    client: PlatformClient,
}

impl DunningClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/ar/dunning/poll`
    pub async fn dunning_poll(&self, claims: &VerifiedClaims, body: &DunningPollRequest) -> Result<DunningPollResponse, ClientError> {
        let path = format!("/api/ar/dunning/poll");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
