//! Client methods for the "Invoices" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, build_query_url, parse_response};

/// Typed HTTP client for Invoices endpoints.
pub struct InvoicesClient {
    client: PlatformClient,
}

impl InvoicesClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/ar/invoices`
    pub async fn list_invoices(&self, claims: &VerifiedClaims, customer_id: Option<i32>, subscription_id: Option<i32>, status: Option<String>, limit: Option<i32>, offset: Option<i32>) -> Result<PaginatedResponse<Invoice>, ClientError> {
        let path = format!("/api/ar/invoices");
        #[derive(serde::Serialize)]
        struct Query {
            customer_id: Option<i32>,
            subscription_id: Option<i32>,
            status: Option<String>,
            limit: Option<i32>,
            offset: Option<i32>,
        }
        let query = Query {
            customer_id,
            subscription_id,
            status,
            limit,
            offset,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ar/invoices`
    pub async fn create_invoice(&self, claims: &VerifiedClaims, body: &CreateInvoiceRequest) -> Result<Invoice, ClientError> {
        let path = format!("/api/ar/invoices");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/ar/invoices/{id}`
    pub async fn get_invoice(&self, claims: &VerifiedClaims, id: i32) -> Result<Invoice, ClientError> {
        let path = format!("/api/ar/invoices/{}", id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/ar/invoices/{id}`
    pub async fn update_invoice(&self, claims: &VerifiedClaims, id: i32, body: &UpdateInvoiceRequest) -> Result<Invoice, ClientError> {
        let path = format!("/api/ar/invoices/{}", id);
        let url = path;
        let resp = self.client.put(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ar/invoices/{id}/finalize`
    pub async fn finalize_invoice(&self, claims: &VerifiedClaims, id: i32, body: &FinalizeInvoiceRequest) -> Result<Invoice, ClientError> {
        let path = format!("/api/ar/invoices/{}/finalize", id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
