//! Client methods for the "Reconciliation" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response, parse_empty};

/// Typed HTTP client for Reconciliation endpoints.
pub struct ReconciliationClient {
    client: PlatformClient,
}

impl ReconciliationClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/ar/recon/poll`
    pub async fn recon_poll(&self, claims: &VerifiedClaims, body: &ReconPollRequest) -> Result<(), ClientError> {
        let path = format!("/api/ar/recon/poll");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// POST `/api/ar/recon/run`
    pub async fn recon_run(&self, claims: &VerifiedClaims, body: &ReconRunRequest) -> Result<ReconRunResult, ClientError> {
        let path = format!("/api/ar/recon/run");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ar/recon/schedule`
    pub async fn schedule_recon(&self, claims: &VerifiedClaims, body: &ScheduleReconRequest) -> Result<ScheduledRunResult, ClientError> {
        let path = format!("/api/ar/recon/schedule");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
