//! Client methods for the "Subscriptions" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, build_query_url, parse_response, parse_empty};
use reqwest::Client;

/// Typed HTTP client for Subscriptions endpoints.
pub struct SubscriptionsClient {
    client: Client,
    base_url: String,
    token: String,
}

impl SubscriptionsClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/ar/subscriptions`
    pub async fn list_subscriptions(&self, customer_id: Option<i32>, status: Option<&str>, limit: Option<i32>, offset: Option<i32>) -> Result<(), ClientError> {
        let path = format!("{}/api/ar/subscriptions", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            customer_id: Option<i32>,
            #[serde(skip_serializing_if = "Option::is_none")]
            status: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            limit: Option<i32>,
            #[serde(skip_serializing_if = "Option::is_none")]
            offset: Option<i32>,
        }
        let query = Query {
            customer_id,
            status: status.map(|s| s.to_string()),
            limit,
            offset,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// POST `/api/ar/subscriptions`
    pub async fn create_subscription(&self, body: &CreateSubscriptionRequest) -> Result<Subscription, ClientError> {
        let path = format!("{}/api/ar/subscriptions", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/ar/subscriptions/{id}`
    pub async fn get_subscription(&self, id: i32) -> Result<Subscription, ClientError> {
        let path = format!("{}/api/ar/subscriptions/{}", self.base_url, id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/ar/subscriptions/{id}`
    pub async fn update_subscription(&self, id: i32, body: &UpdateSubscriptionRequest) -> Result<Subscription, ClientError> {
        let path = format!("{}/api/ar/subscriptions/{}", self.base_url, id);
        let url = path;
        let resp = self.client.put(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ar/subscriptions/{id}/cancel`
    pub async fn cancel_subscription(&self, id: i32, body: &CancelSubscriptionRequest) -> Result<Subscription, ClientError> {
        let path = format!("{}/api/ar/subscriptions/{}/cancel", self.base_url, id);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
