//! Client methods for the "TaxReports" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, build_query_url, parse_response, parse_empty};

/// Typed HTTP client for TaxReports endpoints.
pub struct TaxreportsClient {
    client: PlatformClient,
}

impl TaxreportsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/ar/tax/reports/export`
    pub async fn tax_report_export(&self, claims: &VerifiedClaims, from: Option<chrono::NaiveDate>, to: Option<chrono::NaiveDate>, format: Option<&str>) -> Result<(), ClientError> {
        let path = format!("/api/ar/tax/reports/export");
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            from: Option<chrono::NaiveDate>,
            #[serde(skip_serializing_if = "Option::is_none")]
            to: Option<chrono::NaiveDate>,
            #[serde(skip_serializing_if = "Option::is_none")]
            format: Option<String>,
        }
        let query = Query {
            from,
            to,
            format: format.map(|s| s.to_string()),
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// GET `/api/ar/tax/reports/summary`
    pub async fn tax_report_summary(&self, claims: &VerifiedClaims, from: Option<chrono::NaiveDate>, to: Option<chrono::NaiveDate>) -> Result<TaxReportResponse, ClientError> {
        let path = format!("/api/ar/tax/reports/summary");
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            from: Option<chrono::NaiveDate>,
            #[serde(skip_serializing_if = "Option::is_none")]
            to: Option<chrono::NaiveDate>,
        }
        let query = Query {
            from,
            to,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
