//! Type definitions for the AR Service client.
//!
//! Auto-generated by client-codegen — do not edit.

#![allow(unused_imports)]

use serde::{Deserialize, Serialize};
use crate::*;

/// Pagination metadata for list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginationMeta {
    pub page: i64,
    pub page_size: i64,
    pub total_items: i64,
    pub total_pages: i64,
}

/// Generic paginated response envelope.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedResponse<T> {
    pub data: Vec<T>,
    pub pagination: PaginationMeta,
}

/// Simple wrapper for sub-collection list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataResponse<T> {
    pub data: Vec<T>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AddPaymentMethodRequest {
    pub ar_customer_id: i32,
    pub tilled_payment_method_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingSnapshot {
    pub app_id: String,
    pub currency: String,
    pub current_minor: i64,
    pub customer_id: i32,
    pub days_1_30_minor: i64,
    pub days_31_60_minor: i64,
    pub days_61_90_minor: i64,
    pub days_over_90_minor: i64,
    pub id: i32,
    pub total_outstanding_minor: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllocatePaymentRequest {
    pub amount_cents: i32,
    pub currency: String,
    pub customer_id: i32,
    pub idempotency_key: String,
    pub payment_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllocationResult {
    pub allocated_amount_cents: i32,
    pub allocations: Vec<AllocationRow>,
    pub payment_id: String,
    pub strategy: String,
    pub unallocated_amount_cents: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllocationRow {
    pub amount_cents: i32,
    pub id: i32,
    pub invoice_id: i32,
    pub strategy: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillUsageHttpRequest {
    pub correlation_id: String,
    pub customer_id: i32,
    pub period_end: chrono::DateTime<chrono::Utc>,
    pub period_start: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CancelSubscriptionRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancel_at_period_end: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CaptureChargeRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount_cents: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CaptureUsageRequest {
    pub customer_id: String,
    pub idempotency_key: uuid::Uuid,
    pub metric_name: String,
    pub period_end: chrono::DateTime<chrono::Utc>,
    pub period_start: chrono::DateTime<chrono::Utc>,
    pub quantity: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<i32>,
    pub unit: String,
    pub unit_price_minor: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Charge {
    pub amount_cents: i32,
    pub app_id: String,
    pub ar_customer_id: i32,
    pub charge_type: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_message: Option<String>,
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoice_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_reference: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_date: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_frequency: Option<String>,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tilled_charge_id: Option<String>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weight_amount: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateChargeRequest {
    pub amount_cents: i32,
    pub ar_customer_id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub charge_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    pub reason: String,
    pub reference_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_date: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateCustomerRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_customer_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_id: Option<uuid::Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateInvoiceRequest {
    pub amount_cents: i32,
    pub ar_customer_id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub billing_period_end: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub billing_period_start: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compliance_codes: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line_item_details: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateJurisdictionRequest {
    pub country_code: String,
    pub jurisdiction_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub postal_pattern: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_type: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateRefundRequest {
    pub amount_cents: i32,
    pub charge_id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub reference_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateRuleRequest {
    pub effective_from: chrono::NaiveDate,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effective_to: Option<chrono::NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flat_amount_minor: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_exempt: Option<bool>,
    pub jurisdiction_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    pub rate: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_code: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateSubscriptionRequest {
    pub ar_customer_id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interval_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub interval_unit: Option<SubscriptionInterval>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_id: Option<uuid::Uuid>,
    pub payment_method_id: String,
    pub plan_id: String,
    pub plan_name: String,
    pub price_cents: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Customer {
    pub app_id: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_payment_method_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delinquent_since: Option<chrono::DateTime<chrono::Utc>>,
    pub email: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_customer_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grace_period_end: Option<chrono::DateTime<chrono::Utc>>,
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_retry_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_method_type: Option<String>,
    pub retry_attempt_count: i32,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tilled_customer_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update_source: Option<String>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Dispute {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount_cents: Option<i32>,
    pub app_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub charge_id: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<chrono::DateTime<chrono::Utc>>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evidence_due_by: Option<chrono::DateTime<chrono::Utc>>,
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub opened_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason_code: Option<String>,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tilled_charge_id: Option<String>,
    pub tilled_dispute_id: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningPollRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_size: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DunningPollResponse {
    pub outcomes: Vec<serde_json::Value>,
    pub processed: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    pub app_id: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<String>,
    pub event_type: String,
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
    pub source: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinalizeInvoiceRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Invoice {
    pub amount_cents: i32,
    pub app_id: String,
    pub ar_customer_id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub billing_period_end: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub billing_period_start: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compliance_codes: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hosted_url: Option<String>,
    pub id: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line_item_details: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<chrono::DateTime<chrono::Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_id: Option<uuid::Uuid>,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscription_id: Option<i32>,
    pub tilled_invoice_id: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueCreditNoteRequest {
    pub amount_minor: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    pub correlation_id: String,
    pub credit_note_id: uuid::Uuid,
    pub currency: String,
    pub customer_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub issued_by: Option<String>,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JurisdictionResponse {
    pub app_id: String,
    pub country_code: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: uuid::Uuid,
    pub is_active: bool,
    pub jurisdiction_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub postal_pattern: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state_code: Option<String>,
    pub tax_type: String,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

