//! Client methods for the "QBO Invoice" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{parse_response, ClientError, PlatformClient, VerifiedClaims};

/// Typed HTTP client for QBO Invoice endpoints.
pub struct QboInvoiceClient {
    client: PlatformClient,
}

impl QboInvoiceClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/integrations/qbo/invoice/{invoice_id}/update`
    pub async fn update_invoice(
        &self,
        claims: &VerifiedClaims,
        invoice_id: &str,
        body: &UpdateInvoiceRequest,
    ) -> Result<UpdateInvoiceResponse, ClientError> {
        let path = format!("/api/integrations/qbo/invoice/{}/update", invoice_id);
        let url = path;
        let resp = self
            .client
            .post(&url, body, claims)
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
