//! Client methods for the "Webhooks" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use platform_sdk::{ClientError, parse_empty};
use reqwest::Client;

/// Typed HTTP client for Webhooks endpoints.
pub struct WebhooksClient {
    client: Client,
    base_url: String,
    token: String,
}

impl WebhooksClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// POST `/api/webhooks/inbound/{system}`
    pub async fn inbound_webhook(&self, system: &str) -> Result<(), ClientError> {
        let path = format!("{}/api/webhooks/inbound/{}", self.base_url, system);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
