//! Client methods for the "Cycle Counts" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response, parse_empty};

/// Typed HTTP client for Cycle Counts endpoints.
pub struct CycleCountsClient {
    client: PlatformClient,
}

impl CycleCountsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/inventory/cycle-count-tasks`
    pub async fn post_cycle_count_task(&self, claims: &VerifiedClaims, body: &CreateTaskRequest) -> Result<CreateTaskResult, ClientError> {
        let path = format!("/api/inventory/cycle-count-tasks");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/inventory/cycle-count-tasks/{task_id}/approve`
    pub async fn post_cycle_count_approve(&self, claims: &VerifiedClaims, task_id: uuid::Uuid, body: &ApproveBody) -> Result<(), ClientError> {
        let path = format!("/api/inventory/cycle-count-tasks/{}/approve", task_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// POST `/api/inventory/cycle-count-tasks/{task_id}/submit`
    pub async fn post_cycle_count_submit(&self, claims: &VerifiedClaims, task_id: uuid::Uuid, body: &SubmitBody) -> Result<(), ClientError> {
        let path = format!("/api/inventory/cycle-count-tasks/{}/submit", task_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
