//! Client methods for the "Issues" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, parse_response};
use reqwest::Client;

/// Typed HTTP client for Issues endpoints.
pub struct IssuesClient {
    client: Client,
    base_url: String,
    token: String,
}

impl IssuesClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// POST `/api/inventory/issues`
    pub async fn post_issue(&self, body: &IssueRequest) -> Result<IssueResult, ClientError> {
        let path = format!("{}/api/inventory/issues", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
