//! Client methods for the "Items" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, build_query_url, parse_response};

/// Typed HTTP client for Items endpoints.
pub struct ItemsClient {
    client: PlatformClient,
}

impl ItemsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/inventory/items`
    pub async fn list_items(&self, claims: &VerifiedClaims, search: Option<&str>, tracking_mode: Option<&str>, make_buy: Option<&str>, active: Option<bool>, page: Option<i64>, page_size: Option<i64>) -> Result<PaginatedResponse<Item>, ClientError> {
        let path = format!("/api/inventory/items");
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            search: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            tracking_mode: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            make_buy: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            active: Option<bool>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page: Option<i64>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page_size: Option<i64>,
        }
        let query = Query {
            search: search.map(|s| s.to_string()),
            tracking_mode: tracking_mode.map(|s| s.to_string()),
            make_buy: make_buy.map(|s| s.to_string()),
            active,
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/inventory/items`
    pub async fn create_item(&self, claims: &VerifiedClaims, body: &CreateItemRequest) -> Result<Item, ClientError> {
        let path = format!("/api/inventory/items");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/inventory/items/{id}`
    pub async fn get_item(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<Item, ClientError> {
        let path = format!("/api/inventory/items/{}", id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/inventory/items/{id}`
    pub async fn update_item(&self, claims: &VerifiedClaims, id: uuid::Uuid, body: &UpdateItemRequest) -> Result<Item, ClientError> {
        let path = format!("/api/inventory/items/{}", id);
        let url = path;
        let resp = self.client.put(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/inventory/items/{id}/deactivate`
    pub async fn deactivate_item(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<Item, ClientError> {
        let path = format!("/api/inventory/items/{}/deactivate", id);
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/inventory/items/{id}/make-buy`
    pub async fn put_make_buy(&self, claims: &VerifiedClaims, id: uuid::Uuid, body: &SetMakeBuyRequest) -> Result<Item, ClientError> {
        let path = format!("/api/inventory/items/{}/make-buy", id);
        let url = path;
        let resp = self.client.put(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
