//! Generated typed client for the Inventory Service service.
//!
//! Auto-generated by client-codegen — do not edit.

pub mod types_1;
pub mod types_2;
pub mod types_3;
pub mod adjustments;
pub mod cycle_counts;
pub mod expiry;
pub mod history;
pub mod issues;
pub mod items;
pub mod labels;
pub mod locations;
pub mod lot_genealogy;
pub mod lots_serials;
pub mod receipts;
pub mod reorder_policies;
pub mod reservations;
pub mod revisions;
pub mod status_transfers;
pub mod traceability;
pub mod transfers;
pub mod uom;
pub mod valuation;

pub use types_1::*;
pub use types_2::*;
pub use types_3::*;
pub use adjustments::AdjustmentsClient;
pub use cycle_counts::CycleCountsClient;
pub use expiry::ExpiryClient;
pub use history::HistoryClient;
pub use issues::IssuesClient;
pub use items::ItemsClient;
pub use labels::LabelsClient;
pub use locations::LocationsClient;
pub use lot_genealogy::LotGenealogyClient;
pub use lots_serials::LotsSerialsClient;
pub use receipts::ReceiptsClient;
pub use reorder_policies::ReorderPoliciesClient;
pub use reservations::ReservationsClient;
pub use revisions::RevisionsClient;
pub use status_transfers::StatusTransfersClient;
pub use traceability::TraceabilityClient;
pub use transfers::TransfersClient;
pub use uom::UomClient;
pub use valuation::ValuationClient;

// -- PlatformService trait impls (connects to SDK VerticalBuilder) --

impl platform_sdk::PlatformService for AdjustmentsClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for CycleCountsClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for ExpiryClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for HistoryClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for IssuesClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for ItemsClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for LabelsClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for LocationsClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for LotGenealogyClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for LotsSerialsClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for ReceiptsClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for ReorderPoliciesClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for ReservationsClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for RevisionsClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for StatusTransfersClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for TraceabilityClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for TransfersClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for UomClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for ValuationClient {
    const SERVICE_NAME: &'static str = "inventory";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

