//! Client methods for the "Locations" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response};

/// Typed HTTP client for Locations endpoints.
pub struct LocationsClient {
    client: PlatformClient,
}

impl LocationsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/inventory/locations`
    pub async fn create_location(&self, claims: &VerifiedClaims, body: &CreateLocationRequest) -> Result<Location, ClientError> {
        let path = format!("/api/inventory/locations");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/inventory/locations/{id}`
    pub async fn get_location(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<Location, ClientError> {
        let path = format!("/api/inventory/locations/{}", id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/inventory/locations/{id}`
    pub async fn update_location(&self, claims: &VerifiedClaims, id: uuid::Uuid, body: &UpdateLocationRequest) -> Result<Location, ClientError> {
        let path = format!("/api/inventory/locations/{}", id);
        let url = path;
        let resp = self.client.put(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/inventory/locations/{id}/deactivate`
    pub async fn deactivate_location(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<Location, ClientError> {
        let path = format!("/api/inventory/locations/{}/deactivate", id);
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/inventory/warehouses/{warehouse_id}/locations`
    pub async fn list_locations(&self, claims: &VerifiedClaims, warehouse_id: uuid::Uuid) -> Result<PaginatedResponse<Location>, ClientError> {
        let path = format!("/api/inventory/warehouses/{}/locations", warehouse_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
