//! Client methods for the "Receipts" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response};

/// Typed HTTP client for Receipts endpoints.
pub struct ReceiptsClient {
    client: PlatformClient,
}

impl ReceiptsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/inventory/batch-receipts`
    pub async fn post_batch_receipts(&self, claims: &VerifiedClaims, body: &BatchReceiptRequest) -> Result<BatchReceiptResponse, ClientError> {
        let path = format!("/api/inventory/batch-receipts");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/inventory/receipts`
    pub async fn post_receipt(&self, claims: &VerifiedClaims, body: &ReceiptRequest) -> Result<ReceiptResult, ClientError> {
        let path = format!("/api/inventory/receipts");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
