//! Client methods for the "Revisions" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, build_query_url, parse_response};
use reqwest::Client;

/// Typed HTTP client for Revisions endpoints.
pub struct RevisionsClient {
    client: Client,
    base_url: String,
    token: String,
}

impl RevisionsClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/inventory/items/{item_id}/revisions`
    pub async fn get_list_revisions(&self, item_id: uuid::Uuid) -> Result<PaginatedResponse<ItemRevision>, ClientError> {
        let path = format!("{}/api/inventory/items/{}/revisions", self.base_url, item_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/inventory/items/{item_id}/revisions`
    pub async fn post_create_revision(&self, item_id: uuid::Uuid, body: &CreateRevisionRequest) -> Result<ItemRevision, ClientError> {
        let path = format!("{}/api/inventory/items/{}/revisions", self.base_url, item_id);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/inventory/items/{item_id}/revisions/at`
    pub async fn get_revision_at(&self, item_id: uuid::Uuid, t: Option<&str>) -> Result<ItemRevision, ClientError> {
        let path = format!("{}/api/inventory/items/{}/revisions/at", self.base_url, item_id);
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            t: Option<String>,
        }
        let query = Query {
            t: t.map(|s| s.to_string()),
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/inventory/items/{item_id}/revisions/{revision_id}/activate`
    pub async fn post_activate_revision(&self, item_id: uuid::Uuid, revision_id: uuid::Uuid, body: &ActivateRevisionRequest) -> Result<ItemRevision, ClientError> {
        let path = format!("{}/api/inventory/items/{}/revisions/{}/activate", self.base_url, item_id, revision_id);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/inventory/items/{item_id}/revisions/{revision_id}/policy-flags`
    pub async fn put_revision_policy(&self, item_id: uuid::Uuid, revision_id: uuid::Uuid, body: &UpdateRevisionPolicyRequest) -> Result<ItemRevision, ClientError> {
        let path = format!("{}/api/inventory/items/{}/revisions/{}/policy-flags", self.base_url, item_id, revision_id);
        let url = path;
        let resp = self.client.put(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
