//! Type definitions for the Inventory Service client.
//!
//! Auto-generated by client-codegen — do not edit.

#![allow(unused_imports)]

use serde::{Deserialize, Serialize};
use serde_json::Value;
use crate::*;

/// Pagination metadata for list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginationMeta {
    pub page: i64,
    pub page_size: i64,
    pub total_items: i64,
    pub total_pages: i64,
}

/// Generic paginated response envelope.
///
/// Local definition without `ToSchema` bound — client crates don't need
/// OpenAPI schema derivation. Wire-compatible with `platform_http_contracts::PaginatedResponse`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedResponse<T> {
    pub data: Vec<T>,
    pub pagination: PaginationMeta,
}

/// Simple wrapper for sub-collection list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataResponse<T> {
    pub data: Vec<T>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivateRevisionRequest {
    /// Identity of the actor performing this change (for audit trail).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    pub effective_from: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effective_to: Option<chrono::DateTime<chrono::Utc>>,
    pub idempotency_key: String,
    pub tenant_id: String,
}

/// Input for POST /api/inventory/adjustments
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdjustRequest {
    /// When true, allows a negative delta even if it would drive on_hand below zero.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub allow_negative: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    /// Caller-supplied idempotency key (required; scoped per tenant)
    pub idempotency_key: String,
    pub item_id: uuid::Uuid,
    /// Optional storage location within the warehouse (bin, shelf, zone).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_id: Option<uuid::Uuid>,
    /// Signed quantity change (positive = gain, negative = shrinkage/write-off).
    pub quantity_delta: i64,
    /// Human-readable reason for the adjustment (required).
    pub reason: String,
    pub tenant_id: String,
    pub warehouse_id: uuid::Uuid,
}

/// Result returned on successful or replayed adjustment
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdjustResult {
    pub adjusted_at: chrono::DateTime<chrono::Utc>,
    /// Stable business key for this adjustment (inv_adjustments.id)
    pub adjustment_id: uuid::Uuid,
    /// Outbox event id
    pub event_id: uuid::Uuid,
    pub item_id: uuid::Uuid,
    /// BIGSERIAL ledger row id
    pub ledger_entry_id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_id: Option<uuid::Uuid>,
    pub quantity_delta: i64,
    pub reason: String,
    pub tenant_id: String,
    pub warehouse_id: uuid::Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApproveBody {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    pub idempotency_key: String,
}

/// One FIFO layer consumed during an issue.
/// 
/// `extended_cost_minor` is precomputed: `quantity * unit_cost_minor`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConsumedLayer {
    /// Precomputed: quantity × unit_cost_minor
    pub extended_cost_minor: i64,
    pub layer_id: uuid::Uuid,
    /// Units drawn from this layer (always > 0)
    pub quantity: i64,
    /// Cost per unit from this layer, minor currency units
    pub unit_cost_minor: i64,
}

/// Input for POST /api/inventory/items/:id/uom-conversions
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateConversionRequest {
    /// Multiply from_uom quantity by this factor to get to_uom quantity. Must be > 0.
    pub factor: f64,
    pub from_uom_id: uuid::Uuid,
    pub tenant_id: String,
    pub to_uom_id: uuid::Uuid,
}

/// Input for POST /api/inventory/items
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateItemRequest {
    /// GL account ref for COGS expense (e.g. "5000")
    pub cogs_account_ref: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// GL account ref for inventory asset (e.g. "1200")
    pub inventory_account_ref: String,
    /// Manufacturing classification: "make" | "buy" (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub make_buy: Option<String>,
    pub name: String,
    pub sku: String,
    pub tenant_id: String,
    /// Lot/serial tracking mode. Required; immutable after creation.
    pub tracking_mode: TrackingMode,
    /// Unit of measure, defaults to "ea"
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uom: Option<String>,
    /// GL account ref for purchase price variance (e.g. "5010")
    pub variance_account_ref: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateLocationRequest {
    pub code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub name: String,
    pub tenant_id: String,
    pub warehouse_id: uuid::Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateReorderPolicyRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    pub item_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_qty: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub reorder_point: i64,
    pub safety_stock: i64,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateRevisionRequest {
    /// Identity of the actor performing this change (for audit trail).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    pub change_reason: String,
    pub cogs_account_ref: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub idempotency_key: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inspection_required: Option<bool>,
    pub inventory_account_ref: String,
    pub item_id: uuid::Uuid,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shelf_life_days: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shelf_life_enforced: Option<bool>,
    pub tenant_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub traceability_level: Option<String>,
    pub uom: String,
    pub variance_account_ref: String,
}

/// Request to build a valuation snapshot.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateSnapshotRequest {
    /// Point-in-time for FIFO layer evaluation
    pub as_of: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    pub currency: String,
    pub idempotency_key: String,
    /// None = warehouse-level roll-up; Some = location-scoped header
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_id: Option<uuid::Uuid>,
    pub tenant_id: String,
    pub warehouse_id: uuid::Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateTaskRequest {
    /// Required when scope = partial; ignored (and safe to omit) for full.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item_ids: Option<Vec<uuid::Uuid>>,
    pub location_id: uuid::Uuid,
    pub scope: TaskScope,
    pub tenant_id: String,
    pub warehouse_id: uuid::Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateTaskResult {
    pub line_count: i64,
    pub lines: Vec<TaskLine>,
    pub location_id: uuid::Uuid,
    pub scope: TaskScope,
    pub status: String,
    pub task_id: uuid::Uuid,
    pub tenant_id: String,
    pub warehouse_id: uuid::Uuid,
}

/// Input for POST /api/inventory/uoms
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateUomRequest {
    pub code: String,
    pub name: String,
    pub tenant_id: String,
}

/// Input for POST /api/inventory/reservations/{reservation_id}/fulfill
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FulfillRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    /// Caller-supplied idempotency key (required; scoped per tenant)
    pub idempotency_key: String,
    /// Business reference (e.g. fulfillment_order_id, order_ref)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_ref: Option<String>,
    /// Optional partial fulfillment quantity (defaults to the full reserved quantity)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i64>,
    /// UUID of the original reserve row to fulfill
    pub reservation_id: uuid::Uuid,
    pub tenant_id: String,
}

/// Result returned on successful or replayed fulfillment
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FulfillResult {
    /// UUID of the outbox event
    pub event_id: uuid::Uuid,
    pub fulfilled_at: chrono::DateTime<chrono::Utc>,
    /// UUID of the compensating fulfillment row
    pub fulfillment_id: uuid::Uuid,
    pub item_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_ref: Option<String>,
    pub quantity: i64,
    /// UUID of the original reservation that was fulfilled
    pub reservation_id: uuid::Uuid,
    pub tenant_id: String,
    pub warehouse_id: uuid::Uuid,
}

/// A genealogy edge returned by query functions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenealogyEdge {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<uuid::Uuid>,
    pub child_lot_id: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub occurred_at: chrono::DateTime<chrono::Utc>,
    pub operation_id: uuid::Uuid,
    pub parent_lot_id: uuid::Uuid,
    pub quantity: i64,
    pub tenant_id: String,
    pub transformation: String,
    pub unit: String,
}

/// Result returned on successful split or merge.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenealogyResult {
    pub edge_count: i64,
    pub event_id: uuid::Uuid,
    pub operation_id: uuid::Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateLabelRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor_id: Option<uuid::Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub barcode_format: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    /// Optional extra data merged into the label payload (e.g. lot_code).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extra: Option<serde_json::Value>,
    pub idempotency_key: String,
    pub item_id: uuid::Uuid,
    pub label_type: String,
    pub revision_id: uuid::Uuid,
    pub tenant_id: String,
}

/// The three mutually-exclusive status buckets for stock units.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum InvItemStatus {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "quarantine")]
    Quarantine,
    #[serde(rename = "damaged")]
    Damaged,
}

/// A named lot grouping a batch of items received together.
/// 
/// Lots are unique per (tenant_id, item_id, lot_code).
/// Created on receipt; immutable thereafter (lot_code and item_id never change).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InventoryLot {
    /// Optional free-form metadata stored as JSON (e.g. expiry date, supplier info).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    /// First-class lot expiry date used for policy enforcement and alerting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_on: Option<chrono::NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry_set_at: Option<chrono::DateTime<chrono::Utc>>,
    /// Source of expiry assignment: manual or policy.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry_source: Option<String>,
    pub id: uuid::Uuid,
    pub item_id: uuid::Uuid,
    /// Human-readable lot identifier (e.g. "LOT-2026-001", supplier batch code).
    pub lot_code: String,
    pub tenant_id: String,
}

/// Input for POST /api/inventory/issues
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    pub currency: String,
    /// Caller-supplied idempotency key (required; scoped per tenant)
    pub idempotency_key: String,
    pub item_id: uuid::Uuid,
    /// Optional storage location to issue from. When set, availability is
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_id: Option<uuid::Uuid>,
    /// Required for Lot-tracked items. FIFO consumption is restricted to this lot only.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lot_code: Option<String>,
    /// Quantity to issue (must be > 0 for None/Lot-tracked items).
    pub quantity: i64,
    /// Required for Serial-tracked items. Each code must be on_hand for this item.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub serial_codes: Option<serde_json::Value>,
    pub source_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_line_id: Option<String>,
    pub source_module: String,
    pub source_type: String,
    pub tenant_id: String,
    /// UoM id for the input `quantity`. When present, `quantity` is in this unit
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uom_id: Option<uuid::Uuid>,
    pub warehouse_id: uuid::Uuid,
}

/// Result returned on successful or replayed issue
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueResult {
    pub consumed_layers: Vec<ConsumedLayer>,
    pub currency: String,
    /// Event id used in outbox
    pub event_id: uuid::Uuid,
    /// Stable business key for this issue (= ledger entry_id)
    pub issue_line_id: uuid::Uuid,
    pub issued_at: chrono::DateTime<chrono::Utc>,
    pub item_id: uuid::Uuid,
    /// BIGSERIAL ledger row id
    pub ledger_entry_id: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub location_id: Option<uuid::Uuid>,
    pub quantity: i64,
    pub source_ref: SourceRef,
    pub tenant_id: String,
    pub total_cost_minor: i64,
    pub warehouse_id: uuid::Uuid,
}

