//! Client methods for the "Generate" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_empty};

/// Typed HTTP client for Generate endpoints.
pub struct GenerateClient {
    client: PlatformClient,
}

impl GenerateClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// POST `/api/pdf/forms/submissions/{id}/generate`
    pub async fn generate_pdf(&self, claims: &VerifiedClaims, id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("/api/pdf/forms/submissions/{}/generate", id);
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
