#!/usr/bin/env bash
# staging_deploy.sh — Deploy pinned images to the staging VM.
#
# Usage:
#   ./scripts/staging_deploy.sh            # Deploy to staging
#   ./scripts/staging_deploy.sh --dry-run  # Show what would happen
#
# Environment:
#   STAGING_HOST  — SSH target (e.g., deploy@staging.example.com). Required for live deploy.
#
# See docs/DEPLOYMENT.md for full staging setup.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

REGISTRY="ghcr.io/7d-solutions"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

# --- Version extraction (same logic as staging_push.sh) ---

extract_version_toml() {
    grep '^version' "$1" | head -1 | sed 's/.*"\(.*\)".*/\1/'
}

extract_version_json() {
    grep '"version"' "$1" | head -1 | sed 's/.*"\([0-9][0-9.]*\)".*/\1/'
}

log() {
    echo "[staging_deploy] $*"
}

# --- Resolve image versions ---

cd "$PROJECT_ROOT"

AUTH_VERSION=$(extract_version_toml "platform/identity-auth/Cargo.toml")
AR_VERSION=$(extract_version_toml "modules/ar/Cargo.toml")
TCP_UI_VERSION=$(extract_version_json "apps/tenant-control-plane-ui/package.json")

AUTH_IMAGE="${REGISTRY}/7d-auth:${AUTH_VERSION}"
AR_IMAGE="${REGISTRY}/7d-ar:${AR_VERSION}"
TCP_UI_IMAGE="${REGISTRY}/7d-tcp-ui:${TCP_UI_VERSION}"

log "Registry: $REGISTRY"
log "Mode: $(if $DRY_RUN; then echo 'DRY RUN'; else echo 'LIVE'; fi)"
echo ""

log "=== Image versions ==="
log "  identity-auth: $AUTH_IMAGE"
log "  ar:            $AR_IMAGE"
log "  tcp-ui:        $TCP_UI_IMAGE"
echo ""

# --- Generate staging compose override ---

COMPOSE_STAGING=$(cat <<YAML
# Auto-generated by staging_deploy.sh — do not edit manually.
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# This file overrides docker-compose.services.yml to use
# pre-built GHCR images instead of local builds.

name: 7d-staging

services:
  # --- Infrastructure (inline for standalone staging) ---
  nats:
    image: nats:2.10-alpine
    command: ["-js", "-sd", "/data"]
    ports:
      - "4222:4222"
    volumes:
      - nats_data:/data
    networks:
      - 7d-staging
    restart: unless-stopped

  auth-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    networks:
      - 7d-staging
    restart: unless-stopped

  ar-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ar_db
      POSTGRES_USER: ar_user
      POSTGRES_PASSWORD: ar_pass
    volumes:
      - ar_pgdata:/var/lib/postgresql/data
    networks:
      - 7d-staging
    restart: unless-stopped

  # --- Application services (pinned GHCR images) ---
  auth:
    image: ${AUTH_IMAGE}
    environment:
      DATABASE_URL: postgres://postgres:postgres@auth-postgres:5432/auth_db
      NATS_URL: nats://nats:4222
      HOST: 0.0.0.0
      PORT: 8080
      RUST_LOG: info
    ports:
      - "8080:8080"
    networks:
      - 7d-staging
    depends_on:
      - auth-postgres
      - nats
    restart: unless-stopped

  ar:
    image: ${AR_IMAGE}
    environment:
      DATABASE_URL: postgres://ar_user:ar_pass@ar-postgres:5432/ar_db
      NATS_URL: nats://nats:4222
      BUS_TYPE: nats
      HOST: 0.0.0.0
      PORT: 8086
      RUST_LOG: info
    ports:
      - "8086:8086"
    networks:
      - 7d-staging
    depends_on:
      - ar-postgres
      - nats
    restart: unless-stopped

  tcp-ui:
    image: ${TCP_UI_IMAGE}
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - 7d-staging
    depends_on:
      - auth
    restart: unless-stopped

volumes:
  nats_data:
  auth_pgdata:
  ar_pgdata:

networks:
  7d-staging:
    driver: bridge
YAML
)

log "=== Generated staging compose ==="
echo "$COMPOSE_STAGING"
echo ""

if $DRY_RUN; then
    log "=== Dry-run deploy plan ==="
    log "  1. Write docker-compose.staging.yml to staging host"
    log "  2. Run: docker compose -f docker-compose.staging.yml pull"
    log "  3. Run: docker compose -f docker-compose.staging.yml up -d"
    echo ""
    log "  Target: \${STAGING_HOST:-<not set>}"
    log "Dry run complete. Nothing was deployed."
    exit 0
fi

# --- Live deploy ---

if [[ -z "${STAGING_HOST:-}" ]]; then
    echo "ERROR: STAGING_HOST environment variable is required for live deploy." >&2
    echo "Set it to the SSH target, e.g.: STAGING_HOST=deploy@staging.example.com" >&2
    exit 1
fi

log "=== Deploying to $STAGING_HOST ==="

# Write compose file to staging host
log "Uploading compose file..."
echo "$COMPOSE_STAGING" | ssh "$STAGING_HOST" 'cat > ~/docker-compose.staging.yml'

# Pull images and restart services
log "Pulling images..."
ssh "$STAGING_HOST" 'cd ~ && docker compose -f docker-compose.staging.yml pull'

log "Starting services..."
ssh "$STAGING_HOST" 'cd ~ && docker compose -f docker-compose.staging.yml up -d'

log "=== Deploy complete ==="
log "  Host: $STAGING_HOST"
log "  Services: auth ($AUTH_VERSION), ar ($AR_VERSION), tcp-ui ($TCP_UI_VERSION)"
