openapi: 3.0.0
info:
  title: GL Service API
  version: 1.0.0
  description: General Ledger Service HTTP API for reporting and querying financial data

servers:
  - url: http://localhost:8090
    description: Local development server

paths:
  /api/health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

  /api/gl/trial-balance:
    get:
      summary: Get trial balance for a tenant and period with optional currency grouping
      description: |
        Returns trial balance report backed by account_balances table (no journal scans).

        **Currency Behavior:**
        - If `currency` parameter is provided: Returns only balances for that currency with single totals
        - If `currency` parameter is omitted: Returns all currencies with per-currency totals in `currency_totals` field

        **Performance:** Backed by account_balances table with indexes. Expected < 500ms at normal scale.
      operationId: getTrialBalance
      parameters:
        - name: tenant_id
          in: query
          required: true
          schema:
            type: string
          description: Tenant identifier
        - name: period_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Accounting period UUID
        - name: currency
          in: query
          required: false
          schema:
            type: string
            pattern: '^[A-Z]{3}$'
          description: Optional currency filter (ISO 4217, e.g., USD, EUR, GBP). If omitted, returns all currencies with per-currency totals.
      responses:
        '200':
          description: Trial balance response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrialBalanceResponse'
        '400':
          description: Bad request (invalid parameters)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/gl/detail:
    get:
      summary: Get GL detail (journal entries with lines) for a tenant and period
      operationId: getGLDetail
      parameters:
        - name: tenant_id
          in: query
          required: true
          schema:
            type: string
          description: Tenant identifier
        - name: period_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Accounting period UUID
        - name: account_code
          in: query
          required: false
          schema:
            type: string
          description: Optional account code filter (e.g., "1000")
        - name: currency
          in: query
          required: false
          schema:
            type: string
            pattern: '^[A-Z]{3}$'
          description: Optional currency filter (ISO 4217, e.g., USD, EUR, GBP)
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Page size (default 50)
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Pagination offset (default 0)
      responses:
        '200':
          description: GL detail response with paginated entries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GLDetailResponse'
        '400':
          description: Bad request (invalid parameters)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Period not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/gl/periods/{period_id}/summary:
    get:
      summary: Get period summary for a tenant and period
      operationId: getPeriodSummary
      parameters:
        - name: period_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Accounting period UUID
        - name: tenant_id
          in: query
          required: true
          schema:
            type: string
          description: Tenant identifier
        - name: currency
          in: query
          required: false
          schema:
            type: string
            pattern: '^[A-Z]{3}$'
          description: Optional currency filter (ISO 4217, e.g., USD, EUR, GBP)
      responses:
        '200':
          description: Period summary response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeriodSummaryResponse'
        '400':
          description: Bad request (invalid parameters)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Period not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/gl/accounts/{account_code}/activity:
    get:
      summary: Get account activity (journal lines) for a specific account
      operationId: getAccountActivity
      parameters:
        - name: account_code
          in: path
          required: true
          schema:
            type: string
          description: Chart of Accounts code (e.g., "1000")
        - name: tenant_id
          in: query
          required: true
          schema:
            type: string
          description: Tenant identifier
        - name: period_id
          in: query
          required: false
          schema:
            type: string
            format: uuid
          description: Optional accounting period UUID (mutually exclusive with date range)
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Optional start date (ISO 8601, required if no period_id)
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Optional end date (ISO 8601, required if no period_id)
        - name: currency
          in: query
          required: false
          schema:
            type: string
            pattern: '^[A-Z]{3}$'
          description: Optional currency filter (ISO 4217, e.g., USD, EUR, GBP)
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Page size (default 50)
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Pagination offset (default 0)
      responses:
        '200':
          description: Account activity response with paginated lines
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountActivityResponse'
        '400':
          description: Bad request (invalid parameters or missing date filter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Period not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    TrialBalanceResponse:
      type: object
      required:
        - tenant_id
        - period_id
        - rows
        - totals
      properties:
        tenant_id:
          type: string
          description: Tenant identifier
        period_id:
          type: string
          format: uuid
          description: Accounting period UUID
        currency:
          type: string
          nullable: true
          pattern: '^[A-Z]{3}$'
          description: Optional currency filter applied (null = all currencies)
        rows:
          type: array
          items:
            $ref: '#/components/schemas/TrialBalanceRow'
          description: Trial balance rows (all accounts with balances)
        totals:
          $ref: '#/components/schemas/TrialBalanceTotals'
        currency_totals:
          type: array
          items:
            $ref: '#/components/schemas/CurrencyTotals'
          nullable: true
          description: Per-currency totals (present when no currency filter is applied). Currencies are sorted alphabetically for deterministic ordering.

    TrialBalanceRow:
      type: object
      required:
        - account_code
        - account_name
        - account_type
        - normal_balance
        - currency
        - debit_total_minor
        - credit_total_minor
        - net_balance_minor
      properties:
        account_code:
          type: string
        account_name:
          type: string
        account_type:
          type: string
          enum: [asset, liability, equity, revenue, expense]
        normal_balance:
          type: string
          enum: [debit, credit]
        currency:
          type: string
        debit_total_minor:
          type: integer
          format: int64
        credit_total_minor:
          type: integer
          format: int64
        net_balance_minor:
          type: integer
          format: int64

    TrialBalanceTotals:
      type: object
      required:
        - total_debits
        - total_credits
        - is_balanced
      properties:
        total_debits:
          type: integer
          format: int64
          description: Sum of all debit amounts (minor units)
        total_credits:
          type: integer
          format: int64
          description: Sum of all credit amounts (minor units)
        is_balanced:
          type: boolean
          description: Whether total debits equal total credits

    CurrencyTotals:
      type: object
      required:
        - currency
        - total_debits
        - total_credits
        - is_balanced
      properties:
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
          description: Currency code (ISO 4217)
        total_debits:
          type: integer
          format: int64
          description: Sum of all debit amounts for this currency (minor units)
        total_credits:
          type: integer
          format: int64
          description: Sum of all credit amounts for this currency (minor units)
        is_balanced:
          type: boolean
          description: Whether total debits equal total credits for this currency

    PeriodSummaryResponse:
      type: object
      required:
        - tenant_id
        - period_id
        - currency
        - journal_count
        - line_count
        - total_debits_minor
        - total_credits_minor
        - is_balanced
        - data_source
      properties:
        tenant_id:
          type: string
          description: Tenant identifier
        period_id:
          type: string
          format: uuid
          description: Accounting period UUID
        currency:
          type: string
          description: Currency code (ISO 4217) or "MULTI" for multi-currency aggregate
        journal_count:
          type: integer
          format: int32
          description: Total number of journal entries
        line_count:
          type: integer
          format: int32
          description: Total number of journal lines
        total_debits_minor:
          type: integer
          format: int64
          description: Sum of all debit amounts in minor units (cents)
        total_credits_minor:
          type: integer
          format: int64
          description: Sum of all credit amounts in minor units (cents)
        is_balanced:
          type: boolean
          description: Whether total debits equal total credits
        data_source:
          type: string
          enum: [snapshot, computed]
          description: Data source - "snapshot" if from precomputed snapshot, "computed" if calculated from balances
        snapshot_created_at:
          type: string
          format: date-time
          nullable: true
          description: Timestamp when snapshot was created (null if computed)

    GLDetailResponse:
      type: object
      required:
        - tenant_id
        - period_start
        - period_end
        - entries
        - pagination
      properties:
        tenant_id:
          type: string
          description: Tenant identifier
        period_start:
          type: string
          format: date-time
          description: Start of accounting period (ISO 8601)
        period_end:
          type: string
          format: date-time
          description: End of accounting period (ISO 8601)
        entries:
          type: array
          items:
            $ref: '#/components/schemas/GLDetailEntry'
          description: Journal entries with lines
        pagination:
          $ref: '#/components/schemas/PaginationMetadata'

    GLDetailEntry:
      type: object
      required:
        - id
        - posted_at
        - currency
        - source_module
        - lines
      properties:
        id:
          type: string
          format: uuid
          description: Journal entry UUID
        posted_at:
          type: string
          format: date-time
          description: Posting timestamp (ISO 8601)
        description:
          type: string
          nullable: true
          description: Optional entry description
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
          description: Currency code (ISO 4217)
        source_module:
          type: string
          description: Source module (e.g., "ar", "ap", "payroll")
        lines:
          type: array
          items:
            $ref: '#/components/schemas/GLDetailEntryLine'
          description: Journal entry lines

    GLDetailEntryLine:
      type: object
      required:
        - line_no
        - account_code
        - account_name
        - debit_minor
        - credit_minor
      properties:
        line_no:
          type: integer
          format: int32
          description: Line number (ordering within entry)
        account_code:
          type: string
          description: Chart of Accounts code
        account_name:
          type: string
          description: Account name
        debit_minor:
          type: integer
          format: int64
          description: Debit amount in minor units (cents)
        credit_minor:
          type: integer
          format: int64
          description: Credit amount in minor units (cents)
        memo:
          type: string
          nullable: true
          description: Optional line-level memo

    PaginationMetadata:
      type: object
      required:
        - limit
        - offset
        - total_count
        - has_more
      properties:
        limit:
          type: integer
          format: int64
          description: Page size
        offset:
          type: integer
          format: int64
          description: Pagination offset
        total_count:
          type: integer
          format: int64
          description: Total number of entries matching the query
        has_more:
          type: boolean
          description: Whether there are more entries beyond this page

    AccountActivityResponse:
      type: object
      required:
        - tenant_id
        - account_code
        - period_start
        - period_end
        - lines
        - pagination
      properties:
        tenant_id:
          type: string
          description: Tenant identifier
        account_code:
          type: string
          description: Chart of Accounts code
        period_start:
          type: string
          format: date-time
          description: Start of date range (ISO 8601)
        period_end:
          type: string
          format: date-time
          description: End of date range (ISO 8601)
        lines:
          type: array
          items:
            $ref: '#/components/schemas/AccountActivityLine'
          description: Journal lines for the account
        pagination:
          $ref: '#/components/schemas/PaginationMetadata'

    AccountActivityLine:
      type: object
      required:
        - entry_id
        - posted_at
        - currency
        - debit_minor
        - credit_minor
      properties:
        entry_id:
          type: string
          format: uuid
          description: Journal entry UUID
        posted_at:
          type: string
          format: date-time
          description: Posting timestamp (ISO 8601)
        description:
          type: string
          nullable: true
          description: Optional entry description
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
          description: Currency code (ISO 4217)
        debit_minor:
          type: integer
          format: int64
          description: Debit amount in minor units (cents)
        credit_minor:
          type: integer
          format: int64
          description: Credit amount in minor units (cents)
        memo:
          type: string
          nullable: true
          description: Optional line-level memo

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
