#[path = "adjust/mod.rs"]
pub mod adjust_service;
pub mod classifications;
pub mod cycle_count;
pub mod expiry;
pub mod fifo;
pub mod fulfill_service;
pub mod genealogy;
pub mod guards;
pub mod history;
#[path = "issue/mod.rs"]
pub mod issue_service;
pub mod items;
pub mod items_repo;
pub mod labels;
pub mod make_buy;
pub mod locations;
pub mod lots_serials;
pub mod projections;
pub mod receipt_service;
pub mod reorder;
pub mod reservation_service;
pub mod revisions;
pub mod status;
pub mod transfer_service;
pub mod uom;
pub mod valuation;
