//! Client methods for the "Categories" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, parse_response, parse_empty};
use reqwest::Client;

/// Typed HTTP client for Categories endpoints.
pub struct CategoriesClient {
    client: Client,
    base_url: String,
    token: String,
}

impl CategoriesClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/fixed-assets/categories`
    pub async fn list_categories(&self) -> Result<PaginatedResponse<Category>, ClientError> {
        let path = format!("{}/api/fixed-assets/categories", self.base_url);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/fixed-assets/categories`
    pub async fn create_category(&self, body: &CreateCategoryRequest) -> Result<(), ClientError> {
        let path = format!("{}/api/fixed-assets/categories", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// DELETE `/api/fixed-assets/categories/{id}`
    pub async fn deactivate_category(&self, id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("{}/api/fixed-assets/categories/{}", self.base_url, id);
        let url = path;
        let resp = self.client.delete(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// GET `/api/fixed-assets/categories/{id}`
    pub async fn get_category(&self, id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("{}/api/fixed-assets/categories/{}", self.base_url, id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// PUT `/api/fixed-assets/categories/{id}`
    pub async fn update_category(&self, id: uuid::Uuid, body: &UpdateCategoryRequest) -> Result<(), ClientError> {
        let path = format!("{}/api/fixed-assets/categories/{}", self.base_url, id);
        let url = path;
        let resp = self.client.put(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
