//! Client methods for the "Reports" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response};

/// Typed HTTP client for Reports endpoints.
pub struct ReportsClient {
    client: PlatformClient,
}

impl ReportsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/treasury/cash-position`
    pub async fn cash_position(&self, claims: &VerifiedClaims) -> Result<CashPositionResponse, ClientError> {
        let path = format!("/api/treasury/cash-position");
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/treasury/forecast`
    pub async fn forecast(&self, claims: &VerifiedClaims) -> Result<ForecastResponse, ClientError> {
        let path = format!("/api/treasury/forecast");
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
