openapi: 3.0.3

info:
  title: Identity Auth API
  version: 1.0.0
  description: >
    Public authentication and token issuance API for 7D Solutions Platform.
    Standalone identity service using JWKS-based token validation.

servers:
  - url: https://auth.7dsolutions.io
    description: Production
  - url: http://localhost:3000
    description: Local development

paths:

  /health/live:
    get:
      summary: Liveness probe
      description: Returns 200 if service is running
      responses:
        "200":
          description: Service is alive

  /health/ready:
    get:
      summary: Readiness probe
      description: Returns 200 if service is ready to accept traffic
      responses:
        "200":
          description: Service is ready

  /api/auth/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: Registration successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Invalid registration data
        "409":
          description: User already exists

  /api/auth/login:
    post:
      summary: Authenticate user and issue access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: Invalid credentials

  /api/auth/refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequest"
      responses:
        "200":
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: Invalid refresh token

  /api/auth/logout:
    post:
      summary: Logout and invalidate refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshRequest"
      responses:
        "200":
          description: Logout successful
        "401":
          description: Invalid refresh token

  /.well-known/jwks.json:
    get:
      summary: Retrieve JSON Web Key Set
      description: Public keys for JWT signature verification
      responses:
        "200":
          description: JWKS document
          content:
            application/json:
              schema:
                type: object

components:

  schemas:

    RegisterRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    RefreshRequest:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string

    TokenResponse:
      type: object
      required:
        - access_token
        - expires_in
        - token_type
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        expires_in:
          type: integer
        token_type:
          type: string
          example: Bearer
