/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/metering/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingest_events"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metering/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttp/billing-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/ttp/billing-runs */
        post: operations["create_billing_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ttp/service-agreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/ttp/service-agreements */
        get: operations["list_service_agreements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Standard API error envelope.
         *
         *     `error` is a machine-readable code (`not_found`, `validation_error`, etc.).
         *     `message` is human-readable.  `request_id` is populated from the tracing
         *     context already present in request extensions.  `details` carries per-field
         *     errors for 422 responses.
         */
        ApiError: {
            details?: components["schemas"]["FieldError"][] | null;
            error: string;
            message: string;
            request_id?: string | null;
        };
        BillingRunRequest: {
            billing_period: string;
            idempotency_key: string;
        };
        BillingRunResponse: {
            billing_period: string;
            currency: string;
            /** Format: int32 */
            parties_billed: number;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: int64 */
            total_amount_minor: number;
            was_noop: boolean;
        };
        EventItem: {
            dimension: string;
            idempotency_key: string;
            /** Format: date-time */
            occurred_at: string;
            /** Format: int64 */
            quantity: number;
            source_ref?: string | null;
        };
        /** @description A single field-level validation error. */
        FieldError: {
            field: string;
            message: string;
        };
        IngestEventRequest: {
            events: components["schemas"]["EventItem"][];
        };
        IngestEventResponse: {
            /** Format: int32 */
            duplicates: number;
            /** Format: int32 */
            ingested: number;
            results: components["schemas"]["IngestResultItem"][];
        };
        IngestResultItem: {
            /** Format: uuid */
            event_id?: string | null;
            idempotency_key: string;
            was_duplicate: boolean;
        };
        ListServiceAgreementsResponse: {
            count: number;
            items: components["schemas"]["ServiceAgreementItem"][];
            /** Format: uuid */
            tenant_id: string;
        };
        /** @description Full price trace for a billing period. */
        PriceTrace: {
            currency: string;
            line_items: components["schemas"]["TraceLineItem"][];
            period: string;
            /** Format: date */
            period_end: string;
            /** Format: date */
            period_start: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: int64 */
            total_minor: number;
        };
        ServiceAgreementItem: {
            /** Format: uuid */
            agreement_id: string;
            /** Format: int64 */
            amount_minor: number;
            billing_cycle: string;
            currency: string;
            /** Format: date */
            effective_from: string;
            /** Format: date */
            effective_to?: string | null;
            /** Format: uuid */
            party_id: string;
            plan_code: string;
            status: string;
        };
        /** @description A single line in the price trace. */
        TraceLineItem: {
            currency: string;
            dimension: string;
            /** Format: int64 */
            event_count: number;
            /** Format: int64 */
            line_total_minor: number;
            /** Format: int64 */
            total_quantity: number;
            /** Format: int64 */
            unit_price_minor: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ingest_events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestEventRequest"];
            };
        };
        responses: {
            /** @description Events ingested */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestEventResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid authentication */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Ingestion failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_trace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                period: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price trace for period */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceTrace"];
                };
            };
            /** @description Invalid period format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid authentication */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Trace failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_billing_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingRunRequest"];
            };
        };
        responses: {
            /** @description Billing run completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingRunResponse"];
                };
            };
            /** @description Invalid billing period or empty idempotency key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid authentication */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Tenant not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Tenant has no app_id */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Billing run failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_service_agreements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Filter by status (default: "active"). Pass "all" to see every status. */
                status: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service agreements list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListServiceAgreementsResponse"];
                };
            };
            /** @description Invalid status filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Missing or invalid authentication */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
