//! Client methods for the "Parties" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::types::*;
use platform_sdk::{ClientError, build_query_url, parse_response, parse_empty};
use reqwest::Client;

/// Typed HTTP client for Parties endpoints.
pub struct PartiesClient {
    client: Client,
    base_url: String,
    token: String,
}

impl PartiesClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// POST `/api/party/companies`
    pub async fn create_company(&self, body: &CreateCompanyRequest) -> Result<PartyView, ClientError> {
        let path = format!("{}/api/party/companies", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/party/individuals`
    pub async fn create_individual(&self, body: &CreateIndividualRequest) -> Result<PartyView, ClientError> {
        let path = format!("{}/api/party/individuals", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/party/parties`
    pub async fn list_parties(&self, include_inactive: Option<bool>, page: Option<i64>, page_size: Option<i64>) -> Result<PaginatedResponse<Party>, ClientError> {
        let path = format!("{}/api/party/parties", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            include_inactive: Option<bool>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page: Option<i64>,
            #[serde(skip_serializing_if = "Option::is_none")]
            page_size: Option<i64>,
        }
        let query = Query {
            include_inactive,
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/party/parties/search`
    pub async fn search_parties(&self, name: Option<&str>, party_type: Option<&str>, status: Option<&str>, external_system: Option<&str>, external_id: Option<&str>, limit: Option<i64>, offset: Option<i64>) -> Result<PaginatedResponse<Party>, ClientError> {
        let path = format!("{}/api/party/parties/search", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            #[serde(skip_serializing_if = "Option::is_none")]
            name: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            party_type: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            status: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            external_system: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            external_id: Option<String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            limit: Option<i64>,
            #[serde(skip_serializing_if = "Option::is_none")]
            offset: Option<i64>,
        }
        let query = Query {
            name: name.map(|s| s.to_string()),
            party_type: party_type.map(|s| s.to_string()),
            status: status.map(|s| s.to_string()),
            external_system: external_system.map(|s| s.to_string()),
            external_id: external_id.map(|s| s.to_string()),
            limit,
            offset,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/party/parties/{id}`
    pub async fn get_party(&self, id: uuid::Uuid) -> Result<PartyView, ClientError> {
        let path = format!("{}/api/party/parties/{}", self.base_url, id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/party/parties/{id}`
    pub async fn update_party(&self, id: uuid::Uuid, body: &UpdatePartyRequest) -> Result<PartyView, ClientError> {
        let path = format!("{}/api/party/parties/{}", self.base_url, id);
        let url = path;
        let resp = self.client.put(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/party/parties/{id}/deactivate`
    pub async fn deactivate_party(&self, id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("{}/api/party/parties/{}/deactivate", self.base_url, id);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
