//! Client methods for the "Allocations" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_empty};

/// Typed HTTP client for Allocations endpoints.
pub struct AllocationsClient {
    client: PlatformClient,
}

impl AllocationsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/ap/bills/{bill_id}/allocations`
    pub async fn list_allocations(&self, claims: &VerifiedClaims, bill_id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("/api/ap/bills/{}/allocations", bill_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// POST `/api/ap/bills/{bill_id}/allocations`
    pub async fn create_allocation(&self, claims: &VerifiedClaims, bill_id: uuid::Uuid, body: &CreateAllocationRequest) -> Result<(), ClientError> {
        let path = format!("/api/ap/bills/{}/allocations", bill_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// GET `/api/ap/bills/{bill_id}/balance`
    pub async fn get_balance(&self, claims: &VerifiedClaims, bill_id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("/api/ap/bills/{}/balance", bill_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
