//! Client methods for the "Bills" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, parse_response, parse_empty};

/// Typed HTTP client for Bills endpoints.
pub struct BillsClient {
    client: PlatformClient,
}

impl BillsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/ap/bills`
    pub async fn list_bills(&self, claims: &VerifiedClaims) -> Result<PaginatedResponse<VendorBill>, ClientError> {
        let path = format!("/api/ap/bills");
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ap/bills`
    pub async fn create_bill(&self, claims: &VerifiedClaims, body: &CreateBillRequest) -> Result<(), ClientError> {
        let path = format!("/api/ap/bills");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// GET `/api/ap/bills/{bill_id}`
    pub async fn get_bill(&self, claims: &VerifiedClaims, bill_id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("/api/ap/bills/{}", bill_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// POST `/api/ap/bills/{bill_id}/approve`
    pub async fn approve_bill(&self, claims: &VerifiedClaims, bill_id: uuid::Uuid, body: &ApproveBillRequest) -> Result<(), ClientError> {
        let path = format!("/api/ap/bills/{}/approve", bill_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// POST `/api/ap/bills/{bill_id}/match`
    pub async fn match_bill(&self, claims: &VerifiedClaims, bill_id: uuid::Uuid, body: &RunMatchRequest) -> Result<MatchOutcome, ClientError> {
        let path = format!("/api/ap/bills/{}/match", bill_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ap/bills/{bill_id}/tax-quote`
    pub async fn quote_bill_tax(&self, claims: &VerifiedClaims, bill_id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("/api/ap/bills/{}/tax-quote", bill_id);
        let url = path;
        let resp = self.client.post(&url, &serde_json::Value::Null, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// POST `/api/ap/bills/{bill_id}/void`
    pub async fn void_bill(&self, claims: &VerifiedClaims, bill_id: uuid::Uuid, body: &VoidBillRequest) -> Result<(), ClientError> {
        let path = format!("/api/ap/bills/{}/void", bill_id);
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_empty(resp).await
    }
}
