//! Generated typed client for the AP Service service.
//!
//! Auto-generated by client-codegen — do not edit.

pub mod types_1;
pub mod types_2;
pub mod allocations;
pub mod bills;
pub mod payment_runs;
pub mod payment_terms;
pub mod purchase_orders;
pub mod reports;
pub mod tax_reports;
pub mod vendors;

pub use types_1::*;
pub use types_2::*;
pub use allocations::AllocationsClient;
pub use bills::BillsClient;
pub use payment_runs::PaymentRunsClient;
pub use payment_terms::PaymentTermsClient;
pub use purchase_orders::PurchaseOrdersClient;
pub use reports::ReportsClient;
pub use tax_reports::TaxReportsClient;
pub use vendors::VendorsClient;

// -- PlatformService trait impls (connects to SDK VerticalBuilder) --

impl platform_sdk::PlatformService for AllocationsClient {
    const SERVICE_NAME: &'static str = "ap";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for BillsClient {
    const SERVICE_NAME: &'static str = "ap";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for PaymentRunsClient {
    const SERVICE_NAME: &'static str = "ap";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for PaymentTermsClient {
    const SERVICE_NAME: &'static str = "ap";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for PurchaseOrdersClient {
    const SERVICE_NAME: &'static str = "ap";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for ReportsClient {
    const SERVICE_NAME: &'static str = "ap";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for TaxReportsClient {
    const SERVICE_NAME: &'static str = "ap";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

impl platform_sdk::PlatformService for VendorsClient {
    const SERVICE_NAME: &'static str = "ap";
    fn from_platform_client(client: platform_sdk::PlatformClient) -> Self {
        Self::new(client)
    }
}

