//! Client methods for the "Purchase Orders" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, parse_response};
use reqwest::Client;

/// Typed HTTP client for Purchase Orders endpoints.
pub struct PurchaseOrdersClient {
    client: Client,
    base_url: String,
    token: String,
}

impl PurchaseOrdersClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/ap/pos`
    pub async fn list_pos(&self) -> Result<PaginatedResponse<PurchaseOrder>, ClientError> {
        let path = format!("{}/api/ap/pos", self.base_url);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ap/pos`
    pub async fn create_po(&self, body: &CreatePoRequest) -> Result<PurchaseOrderWithLines, ClientError> {
        let path = format!("{}/api/ap/pos", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/ap/pos/{po_id}`
    pub async fn get_po(&self, po_id: uuid::Uuid) -> Result<PurchaseOrderWithLines, ClientError> {
        let path = format!("{}/api/ap/pos/{}", self.base_url, po_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/ap/pos/{po_id}/approve`
    pub async fn approve_po(&self, po_id: uuid::Uuid, body: &ApprovePoRequest) -> Result<PurchaseOrderWithLines, ClientError> {
        let path = format!("{}/api/ap/pos/{}/approve", self.base_url, po_id);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// PUT `/api/ap/pos/{po_id}/lines`
    pub async fn update_po_lines(&self, po_id: uuid::Uuid, body: &UpdatePoLinesRequest) -> Result<PurchaseOrderWithLines, ClientError> {
        let path = format!("{}/api/ap/pos/{}/lines", self.base_url, po_id);
        let url = path;
        let resp = self.client.put(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
