//! Client methods for the "Tax Reports" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, build_query_url, parse_response, parse_empty};
use reqwest::Client;

/// Typed HTTP client for Tax Reports endpoints.
pub struct TaxReportsClient {
    client: Client,
    base_url: String,
    token: String,
}

impl TaxReportsClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/ap/tax/reports/export`
    pub async fn tax_report_export(&self, from: chrono::NaiveDate, to: chrono::NaiveDate, format: Option<&str>) -> Result<(), ClientError> {
        let path = format!("{}/api/ap/tax/reports/export", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            from: chrono::NaiveDate,
            to: chrono::NaiveDate,
            #[serde(skip_serializing_if = "Option::is_none")]
            format: Option<String>,
        }
        let query = Query {
            from,
            to,
            format: format.map(|s| s.to_string()),
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// GET `/api/ap/tax/reports/summary`
    pub async fn tax_report_summary(&self, from: chrono::NaiveDate, to: chrono::NaiveDate) -> Result<ApTaxReportResponse, ClientError> {
        let path = format!("{}/api/ap/tax/reports/summary", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            from: chrono::NaiveDate,
            to: chrono::NaiveDate,
        }
        let query = Query {
            from,
            to,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
