//! Type definitions for the AP Service client.
//!
//! Auto-generated by client-codegen — do not edit.

#![allow(unused_imports)]

use crate::*;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Pagination metadata for list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginationMeta {
    pub page: i64,
    pub page_size: i64,
    pub total_items: i64,
    pub total_pages: i64,
}

/// Generic paginated response envelope.
///
/// Local definition without `ToSchema` bound — client crates don't need
/// OpenAPI schema derivation. Wire-compatible with `platform_http_contracts::PaginatedResponse`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedResponse<T> {
    pub data: Vec<T>,
    pub pagination: PaginationMeta,
}

/// Simple wrapper for sub-collection list endpoints.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataResponse<T> {
    pub data: Vec<T>,
}

/// Complete aging report response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgingReport {
    /// The date used as the aging reference point.
    pub as_of: chrono::NaiveDate,
    /// Bucket totals grouped by currency.
    pub buckets_by_currency: Vec<CurrencyBucket>,
    /// Per-vendor breakdown — present only when `by_vendor=true` was requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vendor_breakdown: Option<serde_json::Value>,
}

/// A single allocation record as stored in ap_allocations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllocationRecord {
    /// Stable external idempotency anchor — caller-generated UUID.
    pub allocation_id: uuid::Uuid,
    /// "partial" or "full" — derived from remaining bill balance at allocation time.
    pub allocation_type: String,
    /// Amount applied in minor currency units (always > 0).
    pub amount_minor: i64,
    pub bill_id: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    /// ISO 4217 currency code.
    pub currency: String,
    /// BIGSERIAL primary key (internal ordering)
    pub id: i64,
    /// Set when this allocation is claimed by a payment run.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_run_id: Option<uuid::Uuid>,
    pub tenant_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApTaxReportResponse {
    pub from: String,
    pub rows: Vec<ApTaxSummaryRow>,
    pub tenant_id: String,
    pub to: String,
    pub total_bills: i64,
    pub total_tax_minor: i64,
}

/// Persisted tax snapshot for an AP vendor bill.
///
/// Records the full quote -> commit -> void lifecycle with provider references
/// and a deterministic quote hash for idempotency.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApTaxSnapshot {
    pub bill_id: uuid::Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub committed_at: Option<chrono::DateTime<chrono::Utc>>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub id: uuid::Uuid,
    pub provider: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_commit_ref: Option<String>,
    pub provider_quote_ref: String,
    pub quote_hash: String,
    pub quoted_at: chrono::DateTime<chrono::Utc>,
    pub status: String,
    pub tax_by_line: serde_json::Value,
    pub tenant_id: String,
    pub total_tax_minor: i64,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub void_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub voided_at: Option<chrono::DateTime<chrono::Utc>>,
}

/// A single row in an AP paid-tax summary report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApTaxSummaryRow {
    pub applied_rate: f64,
    pub bill_count: i64,
    pub jurisdiction: String,
    pub period: String,
    pub tax_type: String,
    pub total_tax_minor: i64,
}

/// Request body to approve a vendor bill.
///
/// Match policy is enforced unless `override_reason` is provided:
///   - Bills in 'open' status (never matched) require an override.
///   - Bills in 'matched' status with tolerance violations require an override.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApproveBillRequest {
    /// Actor approving the bill (for audit attribution)
    pub approved_by: String,
    /// Override reason to bypass match policy. Required when the bill is
    #[serde(skip_serializing_if = "Option::is_none")]
    pub override_reason: Option<String>,
}

/// Request body to approve a purchase order.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovePoRequest {
    /// Actor performing the approval (for event attribution and audit)
    pub approved_by: String,
}

/// Request to assign payment terms to an existing bill.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssignTermsRequest {
    pub term_id: uuid::Uuid,
}

/// Summary of remaining open balance on a bill.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillBalanceSummary {
    pub allocated_minor: i64,
    pub bill_id: uuid::Uuid,
    pub open_balance_minor: i64,
    pub status: String,
    pub total_minor: i64,
}

/// A single line on a vendor bill as returned from the DB.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillLineRecord {
    pub bill_id: uuid::Uuid,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub description: String,
    pub gl_account_code: String,
    pub line_id: uuid::Uuid,
    pub line_total_minor: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub po_line_id: Option<uuid::Uuid>,
    /// Quantity (DOUBLE PRECISION in DB, f64 in Rust)
    pub quantity: f64,
    pub unit_price_minor: i64,
}

/// Request body to apply a payment allocation to a vendor bill.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateAllocationRequest {
    /// Caller-generated stable UUID — used for idempotency.
    pub allocation_id: uuid::Uuid,
    /// Amount to apply in minor currency units (must be > 0).
    pub amount_minor: i64,
    /// ISO 4217 currency code. Must match the bill currency.
    pub currency: String,
    /// Optional: payment run claiming this allocation (may be set later).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_run_id: Option<uuid::Uuid>,
}

/// A single bill line in the creation request.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateBillLineRequest {
    /// Optional description (defaults to "" if not supplied)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// GL account code (defaults to "" if not supplied)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl_account_code: Option<String>,
    /// Optional item reference — informational only, not persisted in this bead
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item_id: Option<uuid::Uuid>,
    /// PO line reference for matching (None for unmatched/non-PO bills)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub po_line_id: Option<uuid::Uuid>,
    pub quantity: f64,
    pub unit_price_minor: i64,
}

/// Request body to create a vendor bill.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateBillRequest {
    /// ISO 4217 currency code
    pub currency: String,
    /// Explicit due date; if None, derived deterministically from vendor payment terms
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_date: Option<chrono::DateTime<chrono::Utc>>,
    /// Actor entering the bill
    pub entered_by: String,
    /// GL fx_rates UUID — supply when bill currency != tenant functional currency.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fx_rate_id: Option<uuid::Uuid>,
    /// Invoice date from the vendor
    pub invoice_date: chrono::DateTime<chrono::Utc>,
    pub lines: Vec<CreateBillLineRequest>,
    /// Optional tax total in minor currency units
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_minor: Option<i64>,
    pub vendor_id: uuid::Uuid,
    /// Vendor's external invoice reference (must be unique per vendor per tenant)
    pub vendor_invoice_ref: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreatePaymentRunBody {
    pub created_by: String,
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_on_or_before: Option<chrono::DateTime<chrono::Utc>>,
    pub payment_method: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub run_id: Option<uuid::Uuid>,
    pub scheduled_date: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vendor_ids: Option<serde_json::Value>,
}

/// Request body to create payment terms.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreatePaymentTermsRequest {
    pub days_due: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Days within which discount applies. Defaults to 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount_days: Option<i32>,
    /// Discount percentage (e.g. 2.0 for 2%). Defaults to 0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount_pct: Option<f64>,
    /// Idempotency key for duplicate prevention.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    /// Installment schedule as a JSON array (optional).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub installment_schedule: Option<serde_json::Value>,
    pub term_code: String,
}

/// A single line in a PO create or update request.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreatePoLineRequest {
    /// Human-readable line description. Required when item_id is absent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// GL expense account code
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gl_account_code: Option<String>,
    /// Optional inventory item UUID reference.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item_id: Option<uuid::Uuid>,
    /// Quantity ordered (must be > 0)
    pub quantity: f64,
    /// Unit of measure (e.g. "each", "kg"); defaults to "each"
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit_of_measure: Option<String>,
    /// Unit price in minor currency units (must be >= 0)
    pub unit_price_minor: i64,
}

/// Request body to create a purchase order (always created as draft).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreatePoRequest {
    /// Actor creating the PO (for event attribution and audit)
    pub created_by: String,
    /// ISO 4217 currency code
    pub currency: String,
    /// Optional expected delivery date
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expected_delivery_date: Option<chrono::DateTime<chrono::Utc>>,
    /// Line items (at least one required)
    pub lines: Vec<CreatePoLineRequest>,
    pub vendor_id: uuid::Uuid,
}

/// Request body to create a new vendor.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CreateVendorRequest {
    /// ISO 4217 currency code
    pub currency: String,
    pub name: String,
    /// Optional link to a Party record in the party-master service.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub party_id: Option<uuid::Uuid>,
    /// Payment method type (e.g. "ach", "wire", "check")
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<String>,
    /// Payment terms in days. Use PaymentTermsPreset for named values.
    pub payment_terms_days: i32,
    /// Remittance email (pointer only, no secrets)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remittance_email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_id: Option<String>,
}

/// Aging bucket totals for a single currency.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CurrencyBucket {
    /// ISO 4217 currency code.
    pub currency: String,
    /// Open balance in the current bucket (not yet overdue), in minor units.
    pub current_minor: i64,
    /// Open balance 1–30 days past due, in minor units.
    pub days_1_30_minor: i64,
    /// Open balance 31–60 days past due, in minor units.
    pub days_31_60_minor: i64,
    /// Open balance 61–90 days past due, in minor units.
    pub days_61_90_minor: i64,
    /// Open balance more than 90 days past due, in minor units.
    pub over_90_minor: i64,
    /// Sum of all buckets = total outstanding for this currency.
    pub total_open_minor: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MatchLineResult {
    pub bill_line_id: uuid::Uuid,
    /// "matched" | "price_variance" | "qty_variance" | "price_and_qty_variance"
    pub match_status: String,
    /// "two_way", "three_way", or "non_po"
    pub match_type: String,
    /// Amount matched at PO price (minor currency units)
    pub matched_amount_minor: i64,
    pub matched_quantity: f64,
    /// PO line matched against (None for non-PO lines)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub po_line_id: Option<uuid::Uuid>,
    /// (bill_price - po_price) × matched_qty (minor currency units; signed)
    pub price_variance_minor: i64,
    /// bill_qty - (received_qty or po_qty); positive means over-billed
    pub qty_variance: f64,
    /// Primary receipt used (None for two_way or non_po)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub receipt_id: Option<uuid::Uuid>,
    pub within_tolerance: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MatchOutcome {
    pub bill_id: uuid::Uuid,
    /// True when all lines are within tolerance
    pub fully_matched: bool,
    pub lines: Vec<MatchLineResult>,
    pub matched_at: chrono::DateTime<chrono::Utc>,
    pub matched_by: String,
    pub po_id: uuid::Uuid,
}

/// Payment run header row from `payment_runs`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentRun {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub created_by: String,
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub executed_at: Option<chrono::DateTime<chrono::Utc>>,
    pub payment_method: String,
    pub run_id: uuid::Uuid,
    pub scheduled_date: chrono::DateTime<chrono::Utc>,
    pub status: String,
    pub tenant_id: String,
    pub total_minor: i64,
}

/// Payment terms record as stored in the database.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentTerms {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub days_due: i32,
    pub description: String,
    pub discount_days: i32,
    pub discount_pct: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub installment_schedule: Option<serde_json::Value>,
    pub is_active: bool,
    pub tenant_id: String,
    pub term_code: String,
    pub term_id: uuid::Uuid,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

/// A single PO line as returned from the DB.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PoLineRecord {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub description: String,
    pub gl_account_code: String,
    /// Inventory item reference — opaque UUID echoed from the create request.
    /// None for description-only lines.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item_id: Option<uuid::Uuid>,
    pub line_id: uuid::Uuid,
    pub line_total_minor: i64,
    pub po_id: uuid::Uuid,
    pub quantity: f64,
    pub unit_of_measure: String,
    pub unit_price_minor: i64,
}

/// Purchase order header record as returned from the DB.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrder {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub created_by: String,
    /// ISO 4217 currency code
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expected_delivery_date: Option<chrono::DateTime<chrono::Utc>>,
    pub po_id: uuid::Uuid,
    /// Human-readable PO number (unique per tenant)
    pub po_number: String,
    /// Lifecycle status: draft, approved, closed, cancelled
    pub status: String,
    pub tenant_id: String,
    /// Total PO value in minor currency units
    pub total_minor: i64,
    pub vendor_id: uuid::Uuid,
}

/// PO with its line items (for GET and POST 201 responses).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurchaseOrderWithLines {
    pub lines: Vec<PoLineRecord>,
    #[serde(flatten)]
    pub purchase_order: PurchaseOrder,
}
