//! Client methods for the "Aging" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, build_query_url, parse_response};
use reqwest::Client;

/// Typed HTTP client for Aging endpoints.
pub struct AgingClient {
    client: Client,
    base_url: String,
    token: String,
}

impl AgingClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// GET `/api/reporting/ap-aging`
    pub async fn get_ap_aging(&self, as_of: chrono::NaiveDate) -> Result<ApAgingReport, ClientError> {
        let path = format!("{}/api/reporting/ap-aging", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            as_of: chrono::NaiveDate,
        }
        let query = Query {
            as_of,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/reporting/ar-aging`
    pub async fn get_ar_aging(&self, as_of: chrono::NaiveDate) -> Result<ArAgingResponse, ClientError> {
        let path = format!("{}/api/reporting/ar-aging", self.base_url);
        #[derive(serde::Serialize)]
        struct Query {
            as_of: chrono::NaiveDate,
        }
        let query = Query {
            as_of,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
