/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/reporting/ap-aging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/reporting/ap-aging — AP aging report from reporting cache. */
        get: operations["get_ap_aging"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/ar-aging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/reporting/ar-aging — AR aging buckets from the reporting cache. */
        get: operations["get_ar_aging"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/reporting/balance-sheet — Balance Sheet as of a given date. */
        get: operations["get_balance_sheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/cashflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/reporting/cashflow — Cash flow statement for a date range. */
        get: operations["get_cashflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/reporting/forecast — probabilistic cash collection forecast. */
        get: operations["get_forecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/reporting/kpis — unified KPI snapshot from reporting caches. */
        get: operations["get_kpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/pl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/reporting/pl — Profit & Loss statement for a date range. */
        get: operations["get_pl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reporting/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/reporting/rebuild — trigger a statement cache rebuild. */
        post: operations["rebuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Complete AP aging report from the reporting cache. */
        ApAgingReport: {
            /** Format: date */
            as_of: string;
            summary_by_currency: components["schemas"]["CurrencySummary"][];
            vendors: components["schemas"]["VendorAgingRow"][];
        };
        /**
         * @description Standard API error envelope.
         *
         *     `error` is a machine-readable code (`not_found`, `validation_error`, etc.).
         *     `message` is human-readable.  `request_id` is populated from the tracing
         *     context already present in request extensions.  `details` carries per-field
         *     errors for 422 responses.
         */
        ApiError: {
            details?: components["schemas"]["FieldError"][] | null;
            error: string;
            message: string;
            request_id?: string | null;
        };
        ArAgingResponse: {
            aging: components["schemas"]["ArAgingSummary"][];
            /** Format: date */
            as_of: string;
            tenant_id: string;
        };
        /** @description A single aging bucket row from the reporting cache. */
        ArAgingRow: {
            /** Format: date */
            as_of: string;
            /** Format: int64 */
            bucket_1_30_minor: number;
            /** Format: int64 */
            bucket_31_60_minor: number;
            /** Format: int64 */
            bucket_61_90_minor: number;
            /** Format: int64 */
            bucket_over_90_minor: number;
            currency: string;
            /** Format: int64 */
            current_minor: number;
            customer_id: string;
            tenant_id: string;
            /** Format: int64 */
            total_minor: number;
        };
        /** @description Aggregated aging summary across all customers for a tenant. */
        ArAgingSummary: {
            /** Format: date */
            as_of: string;
            /** Format: int64 */
            bucket_1_30_minor: number;
            /** Format: int64 */
            bucket_31_60_minor: number;
            /** Format: int64 */
            bucket_61_90_minor: number;
            /** Format: int64 */
            bucket_over_90_minor: number;
            currency: string;
            /** Format: int64 */
            current_minor: number;
            tenant_id: string;
            /** Format: int64 */
            total_minor: number;
        };
        /** @description An open invoice flagged as at-risk (P(30) < 0.40). */
        AtRiskItem: {
            /** Format: int32 */
            age_days: number;
            /** Format: int64 */
            amount_cents: number;
            currency: string;
            customer_id: string;
            invoice_id: string;
            /** Format: double */
            p30: number;
        };
        BTreeMap: {
            [key: string]: number;
        };
        BalanceSheet: {
            /** Format: date */
            as_of: string;
            /** @description Ordered: ["assets", "liabilities", "equity"] */
            sections: components["schemas"]["BsSection"][];
        };
        BsAccountLine: {
            account_code: string;
            account_name: string;
            /**
             * Format: int64
             * @description Minor units. Positive = normal balance for this section's sign convention.
             */
            amount_minor: number;
            currency: string;
        };
        BsSection: {
            accounts: components["schemas"]["BsAccountLine"][];
            section: string;
            /** @description Total per currency across all accounts in this section. */
            total_by_currency: {
                [key: string]: number;
            };
        };
        /** @description Top-level forecast response. */
        CashForecastResponse: {
            /** Format: date-time */
            as_of: string;
            results: components["schemas"]["CurrencyForecast"][];
        };
        CashflowLine: {
            /**
             * Format: int64
             * @description Signed minor units. Positive = cash inflow.
             */
            amount_minor: number;
            currency: string;
            line_code: string;
            line_label: string;
        };
        CashflowSection: {
            activity_type: string;
            lines: components["schemas"]["CashflowLine"][];
            /** @description Total per currency across all lines in this section. */
            total_by_currency: {
                [key: string]: number;
            };
        };
        CashflowStatement: {
            /** Format: date */
            from: string;
            /** @description Net cash change per currency (sum of all sections). */
            net_cash_change_by_currency: {
                [key: string]: number;
            };
            /** @description Ordered: ["operating", "investing", "financing"] */
            sections: components["schemas"]["CashflowSection"][];
            /** Format: date */
            to: string;
        };
        /** @description Currency-grouped forecast result. */
        CurrencyForecast: {
            at_risk: components["schemas"]["AtRiskItem"][];
            currency: string;
            horizons: components["schemas"]["ForecastHorizon"][];
        };
        /** @description Summary totals across all vendors for one currency. */
        CurrencySummary: {
            /** Format: int64 */
            bucket_1_30_minor: number;
            /** Format: int64 */
            bucket_31_60_minor: number;
            /** Format: int64 */
            bucket_61_90_minor: number;
            /** Format: int64 */
            bucket_over_90_minor: number;
            currency: string;
            /** Format: int64 */
            current_minor: number;
            /** Format: int64 */
            total_minor: number;
        };
        /** @description A single field-level validation error. */
        FieldError: {
            field: string;
            message: string;
        };
        /** @description Expected collection for a single forecast horizon. */
        ForecastHorizon: {
            /** Format: int32 */
            days: number;
            /** Format: int64 */
            expected_cents: number;
            /** Format: int64 */
            p25_cents: number;
            /** Format: int64 */
            p75_cents: number;
        };
        /** @description Unified KPI snapshot for a tenant as-of a given date. */
        KpiSnapshot: {
            /** @description Total outstanding AP by currency (all aging buckets summed). */
            ap_total_outstanding: components["schemas"]["BTreeMap"];
            /** @description Total outstanding AR by currency (all aging buckets summed). */
            ar_total_outstanding: components["schemas"]["BTreeMap"];
            /** Format: date */
            as_of: string;
            /** @description Burn YTD: total expenses from trial balance (expense accounts 5xxx-6xxx). */
            burn_ytd: components["schemas"]["BTreeMap"];
            /** @description Cash collected YTD by currency (operating inflows from cashflow cache). */
            cash_collected_ytd: components["schemas"]["BTreeMap"];
            /** @description Inventory valuation, if available from the KPI cache. */
            inventory_value: components["schemas"]["BTreeMap"];
            /** @description Monthly Recurring Revenue, if available from the KPI cache. */
            mrr: components["schemas"]["BTreeMap"];
        };
        PlAccountLine: {
            account_code: string;
            account_name: string;
            /**
             * Format: int64
             * @description Signed minor units. Positive = revenue/expense amount as labelled.
             */
            amount_minor: number;
            currency: string;
        };
        PlSection: {
            accounts: components["schemas"]["PlAccountLine"][];
            section: string;
            /** @description Total per currency across all accounts in this section. */
            total_by_currency: {
                [key: string]: number;
            };
        };
        PlStatement: {
            /** Format: date */
            from: string;
            /** @description Net income (revenue − cogs − expenses) per currency. */
            net_income_by_currency: {
                [key: string]: number;
            };
            /** @description Ordered: ["revenue", "cogs", "expenses"] */
            sections: components["schemas"]["PlSection"][];
            /** Format: date */
            to: string;
        };
        RebuildRequest: {
            /**
             * Format: date
             * @description Start of rebuild range (inclusive), YYYY-MM-DD.
             */
            from: string;
            tenant_id: string;
            /**
             * Format: date
             * @description End of rebuild range (inclusive), YYYY-MM-DD.
             */
            to: string;
        };
        /** @description Summary of a completed snapshot run. */
        SnapshotRunResult: {
            /** Format: date */
            from: string;
            /**
             * Format: int64
             * @description Total rows upserted into rpt_statement_cache.
             */
            rows_upserted: number;
            tenant_id: string;
            /** Format: date */
            to: string;
        };
        /** @description A single vendor's aging buckets for one currency. */
        VendorAgingRow: {
            /** Format: int64 */
            bucket_1_30_minor: number;
            /** Format: int64 */
            bucket_31_60_minor: number;
            /** Format: int64 */
            bucket_61_90_minor: number;
            /** Format: int64 */
            bucket_over_90_minor: number;
            currency: string;
            /** Format: int64 */
            current_minor: number;
            /** Format: int64 */
            total_minor: number;
            vendor_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_ap_aging: {
        parameters: {
            query: {
                as_of: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AP aging report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApAgingReport"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_ar_aging: {
        parameters: {
            query: {
                as_of: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AR aging summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArAgingResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_balance_sheet: {
        parameters: {
            query: {
                as_of: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Balance sheet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceSheet"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_cashflow: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cash flow statement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashflowStatement"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_forecast: {
        parameters: {
            query?: {
                /**
                 * @description Comma-separated horizon days (e.g. "7,14,30,60,90").
                 *     Defaults to "7,14,30,60,90" if omitted.
                 */
                horizons?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cash forecast */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashForecastResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_kpis: {
        parameters: {
            query: {
                as_of: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description KPI snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSnapshot"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    get_pl: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description P&L statement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlStatement"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    rebuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RebuildRequest"];
            };
        };
        responses: {
            /** @description Rebuild completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotRunResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
