//! Client methods for the "Statements" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, build_query_url, parse_response};

/// Typed HTTP client for Statements endpoints.
pub struct StatementsClient {
    client: PlatformClient,
}

impl StatementsClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/reporting/balance-sheet`
    pub async fn get_balance_sheet(&self, claims: &VerifiedClaims, as_of: chrono::NaiveDate) -> Result<BalanceSheet, ClientError> {
        let path = format!("/api/reporting/balance-sheet");
        #[derive(serde::Serialize)]
        struct Query {
            as_of: chrono::NaiveDate,
        }
        let query = Query {
            as_of,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/reporting/cashflow`
    pub async fn get_cashflow(&self, claims: &VerifiedClaims, from: chrono::NaiveDate, to: chrono::NaiveDate) -> Result<CashflowStatement, ClientError> {
        let path = format!("/api/reporting/cashflow");
        #[derive(serde::Serialize)]
        struct Query {
            from: chrono::NaiveDate,
            to: chrono::NaiveDate,
        }
        let query = Query {
            from,
            to,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/reporting/pl`
    pub async fn get_pl(&self, claims: &VerifiedClaims, from: chrono::NaiveDate, to: chrono::NaiveDate) -> Result<PlStatement, ClientError> {
        let path = format!("/api/reporting/pl");
        #[derive(serde::Serialize)]
        struct Query {
            from: chrono::NaiveDate,
            to: chrono::NaiveDate,
        }
        let query = Query {
            from,
            to,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
