//! Client methods for the "BOM" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, PlatformClient, VerifiedClaims, build_query_url, parse_response};

/// Typed HTTP client for BOM endpoints.
pub struct BomClient {
    client: PlatformClient,
}

impl BomClient {
    pub fn new(client: PlatformClient) -> Self {
        Self { client }
    }

    /// GET `/api/bom`
    pub async fn list_boms(&self, claims: &VerifiedClaims, page: i64, page_size: i64) -> Result<PaginatedResponse<BomHeader>, ClientError> {
        let path = format!("/api/bom");
        #[derive(serde::Serialize)]
        struct Query {
            page: i64,
            page_size: i64,
        }
        let query = Query {
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/bom`
    pub async fn post_bom(&self, claims: &VerifiedClaims, body: &CreateBomRequest) -> Result<BomHeader, ClientError> {
        let path = format!("/api/bom");
        let url = path;
        let resp = self.client.post(&url, body, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/bom/by-part/{part_id}`
    pub async fn get_bom_by_part_id(&self, claims: &VerifiedClaims, part_id: uuid::Uuid) -> Result<BomHeader, ClientError> {
        let path = format!("/api/bom/by-part/{}", part_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/bom/{bom_id}`
    pub async fn get_bom(&self, claims: &VerifiedClaims, bom_id: uuid::Uuid) -> Result<BomHeader, ClientError> {
        let path = format!("/api/bom/{}", bom_id);
        let url = path;
        let resp = self.client.get(&url, claims).await.map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
