//! Client methods for the "BOM Lines" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, build_query_url, parse_response, parse_empty};
use reqwest::Client;

/// Typed HTTP client for BOM Lines endpoints.
pub struct BomLinesClient {
    client: Client,
    base_url: String,
    token: String,
}

impl BomLinesClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// DELETE `/api/bom/lines/{line_id}`
    pub async fn delete_line(&self, line_id: uuid::Uuid) -> Result<(), ClientError> {
        let path = format!("{}/api/bom/lines/{}", self.base_url, line_id);
        let url = path;
        let resp = self.client.delete(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_empty(resp).await
    }

    /// PUT `/api/bom/lines/{line_id}`
    pub async fn put_line(&self, line_id: uuid::Uuid, body: &UpdateLineRequest) -> Result<BomLine, ClientError> {
        let path = format!("{}/api/bom/lines/{}", self.base_url, line_id);
        let url = path;
        let resp = self.client.put(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/bom/revisions/{revision_id}/lines`
    pub async fn get_lines(&self, revision_id: uuid::Uuid, page: i64, page_size: i64) -> Result<PaginatedResponse<BomLine>, ClientError> {
        let path = format!("{}/api/bom/revisions/{}/lines", self.base_url, revision_id);
        #[derive(serde::Serialize)]
        struct Query {
            page: i64,
            page_size: i64,
        }
        let query = Query {
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// POST `/api/bom/revisions/{revision_id}/lines`
    pub async fn post_line(&self, revision_id: uuid::Uuid, body: &AddLineRequest) -> Result<BomLine, ClientError> {
        let path = format!("{}/api/bom/revisions/{}/lines", self.base_url, revision_id);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
