//! Client methods for the "ECO" endpoints.
//!
//! Auto-generated by client-codegen — do not edit.

use crate::*;
use platform_sdk::{ClientError, build_query_url, parse_response};
use reqwest::Client;

/// Typed HTTP client for ECO endpoints.
pub struct EcoClient {
    client: Client,
    base_url: String,
    token: String,
}

impl EcoClient {
    pub fn new(
        client: Client,
        base_url: impl Into<String>,
        token: impl Into<String>,
    ) -> Self {
        Self {
            client,
            base_url: base_url.into(),
            token: token.into(),
        }
    }

    /// Replace the bearer token for subsequent requests.
    pub fn set_token(&mut self, token: impl Into<String>) {
        self.token = token.into();
    }

    /// POST `/api/eco`
    pub async fn post_eco(&self, body: &CreateEcoRequest) -> Result<Eco, ClientError> {
        let path = format!("{}/api/eco", self.base_url);
        let url = path;
        let resp = self.client.post(&url)
            .bearer_auth(&self.token)
            .json(body)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/eco/history/{part_id}`
    pub async fn get_eco_history_for_part(&self, part_id: uuid::Uuid, page: i64, page_size: i64) -> Result<PaginatedResponse<Eco>, ClientError> {
        let path = format!("{}/api/eco/history/{}", self.base_url, part_id);
        #[derive(serde::Serialize)]
        struct Query {
            page: i64,
            page_size: i64,
        }
        let query = Query {
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/eco/{eco_id}`
    pub async fn get_eco(&self, eco_id: uuid::Uuid) -> Result<Eco, ClientError> {
        let path = format!("{}/api/eco/{}", self.base_url, eco_id);
        let url = path;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }

    /// GET `/api/eco/{eco_id}/audit`
    pub async fn get_eco_audit(&self, eco_id: uuid::Uuid, page: i64, page_size: i64) -> Result<PaginatedResponse<EcoAuditEntry>, ClientError> {
        let path = format!("{}/api/eco/{}/audit", self.base_url, eco_id);
        #[derive(serde::Serialize)]
        struct Query {
            page: i64,
            page_size: i64,
        }
        let query = Query {
            page,
            page_size,
        };
        let url = build_query_url(&path, &query)?;
        let resp = self.client.get(&url)
            .bearer_auth(&self.token)
            .send()
            .await
            .map_err(ClientError::Network)?;
        parse_response(resp).await
    }
}
